/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-Containers"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_PrivateIE_Field_H_
#define	_NRPPA_PrivateIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_PrivateIE-ID.h"
#include "NRPPA_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PrivateMessage_IEs__value_PR {
	NRPPA_PrivateMessage_IEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_PrivateMessage_IEs__value_PR;

/* NRPPA_PrivateIE-Field */
typedef struct NRPPA_PrivateMessage_IEs {
	NRPPA_PrivateIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PrivateMessage_IEs__value {
		NRPPA_PrivateMessage_IEs__value_PR present;
		union NRPPA_PrivateMessage_IEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PrivateMessage_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PrivateMessage_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PrivateMessage_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PrivateMessage_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PrivateIE_Field_H_ */
#include <asn_internal.h>
