/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_TF_Configuration_H_
#define	_NRPPA_TF_Configuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "NRPPA_SFNInitialisationTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TF_Configuration__sSB_subcarrier_spacing {
	NRPPA_TF_Configuration__sSB_subcarrier_spacing_kHz15	= 0,
	NRPPA_TF_Configuration__sSB_subcarrier_spacing_kHz30	= 1,
	NRPPA_TF_Configuration__sSB_subcarrier_spacing_kHz120	= 2,
	NRPPA_TF_Configuration__sSB_subcarrier_spacing_kHz240	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_TF_Configuration__sSB_subcarrier_spacing;
typedef enum NRPPA_TF_Configuration__sSB_periodicity {
	NRPPA_TF_Configuration__sSB_periodicity_ms5	= 0,
	NRPPA_TF_Configuration__sSB_periodicity_ms10	= 1,
	NRPPA_TF_Configuration__sSB_periodicity_ms20	= 2,
	NRPPA_TF_Configuration__sSB_periodicity_ms40	= 3,
	NRPPA_TF_Configuration__sSB_periodicity_ms80	= 4,
	NRPPA_TF_Configuration__sSB_periodicity_ms160	= 5
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_TF_Configuration__sSB_periodicity;

/* Forward declarations */
struct NRPPA_SSBBurstPosition;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_TF-Configuration */
typedef struct NRPPA_TF_Configuration {
	long	 sSB_frequency;
	long	 sSB_subcarrier_spacing;
	long	 sSB_Transmit_power;
	long	 sSB_periodicity;
	long	 sSB_half_frame_offset;
	long	 sSB_SFN_offset;
	struct NRPPA_SSBBurstPosition	*sSB_BurstPosition;	/* OPTIONAL */
	NRPPA_SFNInitialisationTime_t	*sFN_initialisation_time;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TF_Configuration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_sSB_subcarrier_spacing_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_sSB_periodicity_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TF_Configuration;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TF_Configuration_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TF_Configuration_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TF_Configuration_H_ */
#include <asn_internal.h>
