/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_BandwidthSRS_H_
#define	_NRPPA_BandwidthSRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_BandwidthSRS_PR {
	NRPPA_BandwidthSRS_PR_NOTHING,	/* No components present */
	NRPPA_BandwidthSRS_PR_fR1,
	NRPPA_BandwidthSRS_PR_fR2
	/* Extensions may appear below */
	
} NRPPA_BandwidthSRS_PR;
typedef enum NRPPA_BandwidthSRS__fR1 {
	NRPPA_BandwidthSRS__fR1_kHz5	= 0,
	NRPPA_BandwidthSRS__fR1_kHz10	= 1,
	NRPPA_BandwidthSRS__fR1_kHz20	= 2,
	NRPPA_BandwidthSRS__fR1_kHz40	= 3,
	NRPPA_BandwidthSRS__fR1_kHz50	= 4,
	NRPPA_BandwidthSRS__fR1_kHz80	= 5,
	NRPPA_BandwidthSRS__fR1_kHz100	= 6
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_BandwidthSRS__fR1;
typedef enum NRPPA_BandwidthSRS__fR2 {
	NRPPA_BandwidthSRS__fR2_kHz50	= 0,
	NRPPA_BandwidthSRS__fR2_kHz100	= 1,
	NRPPA_BandwidthSRS__fR2_kHz200	= 2,
	NRPPA_BandwidthSRS__fR2_kHz400	= 3
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_BandwidthSRS__fR2;

/* NRPPA_BandwidthSRS */
typedef struct NRPPA_BandwidthSRS {
	NRPPA_BandwidthSRS_PR present;
	union NRPPA_BandwidthSRS_u {
		long	 fR1;
		long	 fR2;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_BandwidthSRS_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_fR1_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_fR2_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_BandwidthSRS;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_BandwidthSRS_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_BandwidthSRS_1[2];
extern asn_per_constraints_t asn_PER_type_NRPPA_BandwidthSRS_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_BandwidthSRS_H_ */
#include <asn_internal.h>
