/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_ResourceTypePeriodic_H_
#define	_NRPPA_ResourceTypePeriodic_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ResourceTypePeriodic__periodicity {
	NRPPA_ResourceTypePeriodic__periodicity_slot1	= 0,
	NRPPA_ResourceTypePeriodic__periodicity_slot2	= 1,
	NRPPA_ResourceTypePeriodic__periodicity_slot4	= 2,
	NRPPA_ResourceTypePeriodic__periodicity_slot5	= 3,
	NRPPA_ResourceTypePeriodic__periodicity_slot8	= 4,
	NRPPA_ResourceTypePeriodic__periodicity_slot10	= 5,
	NRPPA_ResourceTypePeriodic__periodicity_slot16	= 6,
	NRPPA_ResourceTypePeriodic__periodicity_slot20	= 7,
	NRPPA_ResourceTypePeriodic__periodicity_slot32	= 8,
	NRPPA_ResourceTypePeriodic__periodicity_slot40	= 9,
	NRPPA_ResourceTypePeriodic__periodicity_slot64	= 10,
	NRPPA_ResourceTypePeriodic__periodicity_slot80	= 11,
	NRPPA_ResourceTypePeriodic__periodicity_slot160	= 12,
	NRPPA_ResourceTypePeriodic__periodicity_slot320	= 13,
	NRPPA_ResourceTypePeriodic__periodicity_slot640	= 14,
	NRPPA_ResourceTypePeriodic__periodicity_slot1280	= 15,
	NRPPA_ResourceTypePeriodic__periodicity_slot2560	= 16
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_ResourceTypePeriodic__periodicity;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_ResourceTypePeriodic */
typedef struct NRPPA_ResourceTypePeriodic {
	long	 periodicity;
	long	 offset;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResourceTypePeriodic_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_periodicity_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResourceTypePeriodic;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResourceTypePeriodic_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResourceTypePeriodic_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResourceTypePeriodic_H_ */
#include <asn_internal.h>
