/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_RelativeGeodeticLocation_H_
#define	_NRPPA_RelativeGeodeticLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include "NRPPA_LocationUncertainty.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_RelativeGeodeticLocation__milli_Arc_SecondUnits {
	NRPPA_RelativeGeodeticLocation__milli_Arc_SecondUnits_zerodot03	= 0,
	NRPPA_RelativeGeodeticLocation__milli_Arc_SecondUnits_zerodot3	= 1,
	NRPPA_RelativeGeodeticLocation__milli_Arc_SecondUnits_three	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_RelativeGeodeticLocation__milli_Arc_SecondUnits;
typedef enum NRPPA_RelativeGeodeticLocation__heightUnits {
	NRPPA_RelativeGeodeticLocation__heightUnits_mm	= 0,
	NRPPA_RelativeGeodeticLocation__heightUnits_cm	= 1,
	NRPPA_RelativeGeodeticLocation__heightUnits_m	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_RelativeGeodeticLocation__heightUnits;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_RelativeGeodeticLocation */
typedef struct NRPPA_RelativeGeodeticLocation {
	long	 milli_Arc_SecondUnits;
	long	 heightUnits;
	long	 deltaLatitude;
	long	 deltaLongitude;
	long	 deltaHeight;
	NRPPA_LocationUncertainty_t	 locationUncertainty;
	struct NRPPA_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_RelativeGeodeticLocation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_milli_Arc_SecondUnits_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_heightUnits_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_RelativeGeodeticLocation;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_RelativeGeodeticLocation_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_RelativeGeodeticLocation_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_RelativeGeodeticLocation_H_ */
#include <asn_internal.h>
