/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_PosSIB_Type_H_
#define	_NRPPA_PosSIB_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PosSIB_Type {
	NRPPA_PosSIB_Type_posSibType1_1	= 0,
	NRPPA_PosSIB_Type_posSibType1_2	= 1,
	NRPPA_PosSIB_Type_posSibType1_3	= 2,
	NRPPA_PosSIB_Type_posSibType1_4	= 3,
	NRPPA_PosSIB_Type_posSibType1_5	= 4,
	NRPPA_PosSIB_Type_posSibType1_6	= 5,
	NRPPA_PosSIB_Type_posSibType1_7	= 6,
	NRPPA_PosSIB_Type_posSibType1_8	= 7,
	NRPPA_PosSIB_Type_posSibType2_1	= 8,
	NRPPA_PosSIB_Type_posSibType2_2	= 9,
	NRPPA_PosSIB_Type_posSibType2_3	= 10,
	NRPPA_PosSIB_Type_posSibType2_4	= 11,
	NRPPA_PosSIB_Type_posSibType2_5	= 12,
	NRPPA_PosSIB_Type_posSibType2_6	= 13,
	NRPPA_PosSIB_Type_posSibType2_7	= 14,
	NRPPA_PosSIB_Type_posSibType2_8	= 15,
	NRPPA_PosSIB_Type_posSibType2_9	= 16,
	NRPPA_PosSIB_Type_posSibType2_10	= 17,
	NRPPA_PosSIB_Type_posSibType2_11	= 18,
	NRPPA_PosSIB_Type_posSibType2_12	= 19,
	NRPPA_PosSIB_Type_posSibType2_13	= 20,
	NRPPA_PosSIB_Type_posSibType2_14	= 21,
	NRPPA_PosSIB_Type_posSibType2_15	= 22,
	NRPPA_PosSIB_Type_posSibType2_16	= 23,
	NRPPA_PosSIB_Type_posSibType2_17	= 24,
	NRPPA_PosSIB_Type_posSibType2_18	= 25,
	NRPPA_PosSIB_Type_posSibType2_19	= 26,
	NRPPA_PosSIB_Type_posSibType2_20	= 27,
	NRPPA_PosSIB_Type_posSibType2_21	= 28,
	NRPPA_PosSIB_Type_posSibType2_22	= 29,
	NRPPA_PosSIB_Type_posSibType2_23	= 30,
	NRPPA_PosSIB_Type_posSibType2_24	= 31,
	NRPPA_PosSIB_Type_posSibType2_25	= 32,
	NRPPA_PosSIB_Type_posSibType3_1	= 33,
	NRPPA_PosSIB_Type_posSibType4_1	= 34,
	NRPPA_PosSIB_Type_posSibType5_1	= 35,
	NRPPA_PosSIB_Type_posSibType6_1	= 36,
	NRPPA_PosSIB_Type_posSibType6_2	= 37,
	NRPPA_PosSIB_Type_posSibType6_3	= 38
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_PosSIB_Type;

/* NRPPA_PosSIB-Type */
typedef long	 NRPPA_PosSIB_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_PosSIB_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PosSIB_Type;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_PosSIB_Type_specs_1;
asn_struct_free_f NRPPA_PosSIB_Type_free;
asn_struct_print_f NRPPA_PosSIB_Type_print;
asn_constr_check_f NRPPA_PosSIB_Type_constraint;
ber_type_decoder_f NRPPA_PosSIB_Type_decode_ber;
der_type_encoder_f NRPPA_PosSIB_Type_encode_der;
xer_type_decoder_f NRPPA_PosSIB_Type_decode_xer;
xer_type_encoder_f NRPPA_PosSIB_Type_encode_xer;
jer_type_encoder_f NRPPA_PosSIB_Type_encode_jer;
per_type_decoder_f NRPPA_PosSIB_Type_decode_uper;
per_type_encoder_f NRPPA_PosSIB_Type_encode_uper;
per_type_decoder_f NRPPA_PosSIB_Type_decode_aper;
per_type_encoder_f NRPPA_PosSIB_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PosSIB_Type_H_ */
#include <asn_internal.h>
