/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_ReferencePoint_H_
#define	_NRPPA_ReferencePoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_CoordinateID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ReferencePoint_PR {
	NRPPA_ReferencePoint_PR_NOTHING,	/* No components present */
	NRPPA_ReferencePoint_PR_relativeCoordinateID,
	NRPPA_ReferencePoint_PR_referencePointCoordinate,
	NRPPA_ReferencePoint_PR_referencePointCoordinateHA,
	NRPPA_ReferencePoint_PR_choice_Extension
} NRPPA_ReferencePoint_PR;

/* Forward declarations */
struct NRPPA_NG_RANAccessPointPosition;
struct NRPPA_NGRANHighAccuracyAccessPointPosition;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_ReferencePoint */
typedef struct NRPPA_ReferencePoint {
	NRPPA_ReferencePoint_PR present;
	union NRPPA_ReferencePoint_u {
		NRPPA_CoordinateID_t	 relativeCoordinateID;
		struct NRPPA_NG_RANAccessPointPosition	*referencePointCoordinate;
		struct NRPPA_NGRANHighAccuracyAccessPointPosition	*referencePointCoordinateHA;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ReferencePoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ReferencePoint;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_ReferencePoint_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ReferencePoint_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPA_ReferencePoint_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ReferencePoint_H_ */
#include <asn_internal.h>
