/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#include "NRPPA_NR-PRS-Beam-InformationItem.h"

#include "NRPPA_PRSAngleItem.h"
static int
memb_NRPPA_pRSresourceSetID_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 7L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NRPPA_pRSAngleItem_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 64UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_NRPPA_pRSAngleItem_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPA_pRSresourceSetID_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPA_pRSAngleItem_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  64 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_NRPPA_pRSAngleItem_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPA_PRSAngleItem,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_NRPPA_pRSAngleItem_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_NRPPA_pRSAngleItem_specs_3 = {
	sizeof(struct NRPPA_NR_PRS_Beam_InformationItem__pRSAngleItem),
	offsetof(struct NRPPA_NR_PRS_Beam_InformationItem__pRSAngleItem, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NRPPA_pRSAngleItem_3 = {
	"pRSAngleItem",
	"pRSAngleItem",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_NRPPA_pRSAngleItem_tags_3,
	sizeof(asn_DEF_NRPPA_pRSAngleItem_tags_3)
		/sizeof(asn_DEF_NRPPA_pRSAngleItem_tags_3[0]) - 1, /* 1 */
	asn_DEF_NRPPA_pRSAngleItem_tags_3,	/* Same as above */
	sizeof(asn_DEF_NRPPA_pRSAngleItem_tags_3)
		/sizeof(asn_DEF_NRPPA_pRSAngleItem_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NRPPA_pRSAngleItem_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_NRPPA_pRSAngleItem_3,
	1,	/* Single element */
	&asn_SPC_NRPPA_pRSAngleItem_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NRPPA_NR_PRS_Beam_InformationItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_NR_PRS_Beam_InformationItem, pRSresourceSetID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPA_pRSresourceSetID_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPA_pRSresourceSetID_constraint_1
		},
		0, 0, /* No default value */
		"pRSresourceSetID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_NR_PRS_Beam_InformationItem, pRSAngleItem),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_NRPPA_pRSAngleItem_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPA_pRSAngleItem_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPA_pRSAngleItem_constraint_1
		},
		0, 0, /* No default value */
		"pRSAngleItem"
		},
};
static const ber_tlv_tag_t asn_DEF_NRPPA_NR_PRS_Beam_InformationItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPA_NR_PRS_Beam_InformationItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pRSresourceSetID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pRSAngleItem */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPA_NR_PRS_Beam_InformationItem_specs_1 = {
	sizeof(struct NRPPA_NR_PRS_Beam_InformationItem),
	offsetof(struct NRPPA_NR_PRS_Beam_InformationItem, _asn_ctx),
	asn_MAP_NRPPA_NR_PRS_Beam_InformationItem_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPA_NR_PRS_Beam_InformationItem = {
	"NR-PRS-Beam-InformationItem",
	"NR-PRS-Beam-InformationItem",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPA_NR_PRS_Beam_InformationItem_tags_1,
	sizeof(asn_DEF_NRPPA_NR_PRS_Beam_InformationItem_tags_1)
		/sizeof(asn_DEF_NRPPA_NR_PRS_Beam_InformationItem_tags_1[0]), /* 1 */
	asn_DEF_NRPPA_NR_PRS_Beam_InformationItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPA_NR_PRS_Beam_InformationItem_tags_1)
		/sizeof(asn_DEF_NRPPA_NR_PRS_Beam_InformationItem_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPA_NR_PRS_Beam_InformationItem_1,
	2,	/* Elements count */
	&asn_SPC_NRPPA_NR_PRS_Beam_InformationItem_specs_1	/* Additional specs */
};

