/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_TimeStampSlotIndex_H_
#define	_NRPPA_TimeStampSlotIndex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TimeStampSlotIndex_PR {
	NRPPA_TimeStampSlotIndex_PR_NOTHING,	/* No components present */
	NRPPA_TimeStampSlotIndex_PR_sCS_15,
	NRPPA_TimeStampSlotIndex_PR_sCS_30,
	NRPPA_TimeStampSlotIndex_PR_sCS_60,
	NRPPA_TimeStampSlotIndex_PR_sCS_120,
	NRPPA_TimeStampSlotIndex_PR_choice_extension
} NRPPA_TimeStampSlotIndex_PR;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_TimeStampSlotIndex */
typedef struct NRPPA_TimeStampSlotIndex {
	NRPPA_TimeStampSlotIndex_PR present;
	union NRPPA_TimeStampSlotIndex_u {
		long	 sCS_15;
		long	 sCS_30;
		long	 sCS_60;
		long	 sCS_120;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TimeStampSlotIndex_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TimeStampSlotIndex;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_TimeStampSlotIndex_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TimeStampSlotIndex_1[5];
extern asn_per_constraints_t asn_PER_type_NRPPA_TimeStampSlotIndex_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TimeStampSlotIndex_H_ */
#include <asn_internal.h>
