/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_TrpMeasurementQuality_H_
#define	_NRPPA_TrpMeasurementQuality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TrpMeasurementQuality_PR {
	NRPPA_TrpMeasurementQuality_PR_NOTHING,	/* No components present */
	NRPPA_TrpMeasurementQuality_PR_timingMeasQuality,
	NRPPA_TrpMeasurementQuality_PR_angleMeasQuality,
	NRPPA_TrpMeasurementQuality_PR_choice_Extension
} NRPPA_TrpMeasurementQuality_PR;

/* Forward declarations */
struct NRPPA_TrpMeasurementTimingQuality;
struct NRPPA_TrpMeasurementAngleQuality;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_TrpMeasurementQuality */
typedef struct NRPPA_TrpMeasurementQuality {
	NRPPA_TrpMeasurementQuality_PR present;
	union NRPPA_TrpMeasurementQuality_u {
		struct NRPPA_TrpMeasurementTimingQuality	*timingMeasQuality;
		struct NRPPA_TrpMeasurementAngleQuality	*angleMeasQuality;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TrpMeasurementQuality_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TrpMeasurementQuality;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_TrpMeasurementQuality_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TrpMeasurementQuality_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_TrpMeasurementQuality_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TrpMeasurementQuality_H_ */
#include <asn_internal.h>
