/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-Containers"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_ProtocolIE_Field_H_
#define	_NRPPA_ProtocolIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_ProtocolIE-ID.h"
#include "NRPPA_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "NRPPA_OTDOA-Information-Type-Item.h"
#include "NRPPA_Presence.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "NRPPA_MeasurementQuantities-Item.h"
#include "NRPPA_ResultSS-RSRP.h"
#include "NRPPA_ResultSS-RSRQ.h"
#include "NRPPA_ResultCSI-RSRP.h"
#include "NRPPA_ResultCSI-RSRQ.h"
#include "NRPPA_UL-AoA.h"
#include "NRPPA_TDD-Config-EUTRA-Item.h"
#include "NRPPA_OtherRATMeasurementQuantities-Item.h"
#include "NRPPA_ResultNR.h"
#include "NRPPA_ResultEUTRA.h"
#include "NRPPA_WLANMeasurementQuantities-Item.h"
#include "NRPPA_UE-Measurement-ID.h"
#include "NRPPA_ReportCharacteristics.h"
#include "NRPPA_MeasurementPeriodicity.h"
#include "NRPPA_MeasurementQuantities.h"
#include "NRPPA_OtherRATMeasurementQuantities.h"
#include "NRPPA_WLANMeasurementQuantities.h"
#include "NRPPA_E-CID-MeasurementResult.h"
#include "NRPPA_CriticalityDiagnostics.h"
#include "NRPPA_Cell-Portion-ID.h"
#include "NRPPA_OtherRATMeasurementResult.h"
#include "NRPPA_WLANMeasurementResult.h"
#include "NRPPA_Cause.h"
#include "NRPPA_OTDOA-Information-Type.h"
#include "NRPPA_OTDOACells.h"
#include "NRPPA_Assistance-Information.h"
#include "NRPPA_Broadcast.h"
#include "NRPPA_PositioningBroadcastCells.h"
#include "NRPPA_AssistanceInformationFailureList.h"
#include "NRPPA_RequestedSRSTransmissionCharacteristics.h"
#include "NRPPA_SRSConfiguration.h"
#include "NRPPA_SFNInitialisationTime.h"
#include "NRPPA_Measurement-ID.h"
#include "NRPPA_TRP-MeasurementRequestList.h"
#include "NRPPA_TRPMeasurementQuantities.h"
#include "NRPPA_MeasurementBeamInfoRequest.h"
#include "NRPPA_SystemFrameNumber.h"
#include "NRPPA_SlotNumber.h"
#include "NRPPA_TRP-MeasurementResponseList.h"
#include "NRPPA_TRPList.h"
#include "NRPPA_TRPInformationTypeList.h"
#include "NRPPA_TRPInformationList.h"
#include "NRPPA_SRSType.h"
#include "NRPPA_ActivationTime.h"
#include "NRPPA_AbortTransmission.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_OTDOA_Information_TypeIEs__value_PR {
	NRPPA_OTDOA_Information_TypeIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_OTDOA_Information_TypeIEs__value_PR_OTDOA_Information_Type_Item
} NRPPA_OTDOA_Information_TypeIEs__value_PR;
typedef enum NRPPA_SRSType_ExtIEs__value_PR {
	NRPPA_SRSType_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_SRSType_ExtIEs__value_PR;
typedef enum NRPPA_AbortTransmission_ExtIEs__value_PR {
	NRPPA_AbortTransmission_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_AbortTransmission_ExtIEs__value_PR;
typedef enum NRPPA_Cause_ExtensionIE__value_PR {
	NRPPA_Cause_ExtensionIE__value_PR_NOTHING	/* No components present */
	
} NRPPA_Cause_ExtensionIE__value_PR;
typedef enum NRPPA_DL_PRSMutingPattern_ExtIEs__value_PR {
	NRPPA_DL_PRSMutingPattern_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_DL_PRSMutingPattern_ExtIEs__value_PR;
typedef enum NRPPA_DL_PRSResourceSetARPLocation_ExtIEs__value_PR {
	NRPPA_DL_PRSResourceSetARPLocation_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_DL_PRSResourceSetARPLocation_ExtIEs__value_PR;
typedef enum NRPPA_DL_PRSResourceARPLocation_ExtIEs__value_PR {
	NRPPA_DL_PRSResourceARPLocation_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_DL_PRSResourceARPLocation_ExtIEs__value_PR;
typedef enum NRPPA_GNBRxTxTimeDiffMeas_ExtIEs__value_PR {
	NRPPA_GNBRxTxTimeDiffMeas_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_GNBRxTxTimeDiffMeas_ExtIEs__value_PR;
typedef enum NRPPA_MeasurementQuantities_ItemIEs__value_PR {
	NRPPA_MeasurementQuantities_ItemIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementQuantities_ItemIEs__value_PR_MeasurementQuantities_Item
} NRPPA_MeasurementQuantities_ItemIEs__value_PR;
typedef enum NRPPA_MeasuredResultsValue_ExtensionIE__value_PR {
	NRPPA_MeasuredResultsValue_ExtensionIE__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasuredResultsValue_ExtensionIE__value_PR_ResultSS_RSRP,
	NRPPA_MeasuredResultsValue_ExtensionIE__value_PR_ResultSS_RSRQ,
	NRPPA_MeasuredResultsValue_ExtensionIE__value_PR_ResultCSI_RSRP,
	NRPPA_MeasuredResultsValue_ExtensionIE__value_PR_ResultCSI_RSRQ,
	NRPPA_MeasuredResultsValue_ExtensionIE__value_PR_UL_AoA
} NRPPA_MeasuredResultsValue_ExtensionIE__value_PR;
typedef enum NRPPA_NG_RANCell_ExtensionIE__value_PR {
	NRPPA_NG_RANCell_ExtensionIE__value_PR_NOTHING	/* No components present */
	
} NRPPA_NG_RANCell_ExtensionIE__value_PR;
typedef enum NRPPA_OTDOACell_Information_Item_ExtensionIE__value_PR {
	NRPPA_OTDOACell_Information_Item_ExtensionIE__value_PR_NOTHING,	/* No components present */
	NRPPA_OTDOACell_Information_Item_ExtensionIE__value_PR_TDD_Config_EUTRA_Item
} NRPPA_OTDOACell_Information_Item_ExtensionIE__value_PR;
typedef enum NRPPA_OtherRATMeasurementQuantities_ItemIEs__value_PR {
	NRPPA_OtherRATMeasurementQuantities_ItemIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_OtherRATMeasurementQuantities_ItemIEs__value_PR_OtherRATMeasurementQuantities_Item
} NRPPA_OtherRATMeasurementQuantities_ItemIEs__value_PR;
typedef enum NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__value_PR {
	NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__value_PR_NOTHING,	/* No components present */
	NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__value_PR_ResultNR,
	NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__value_PR_ResultEUTRA
} NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__value_PR;
typedef enum NRPPA_PathlossReferenceSignal_ExtensionIE__value_PR {
	NRPPA_PathlossReferenceSignal_ExtensionIE__value_PR_NOTHING	/* No components present */
	
} NRPPA_PathlossReferenceSignal_ExtensionIE__value_PR;
typedef enum NRPPA_PosResourceSetType_ExtIEs__value_PR {
	NRPPA_PosResourceSetType_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_PosResourceSetType_ExtIEs__value_PR;
typedef enum NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR {
	NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR_NOTHING	/* No components present */
	
} NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR;
typedef enum NRPPA_ReferenceSignal_ExtensionIE__value_PR {
	NRPPA_ReferenceSignal_ExtensionIE__value_PR_NOTHING	/* No components present */
	
} NRPPA_ReferenceSignal_ExtensionIE__value_PR;
typedef enum NRPPA_ReferencePoint_ExtIEs__value_PR {
	NRPPA_ReferencePoint_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_ReferencePoint_ExtIEs__value_PR;
typedef enum NRPPA_ResourceSetType_ExtIEs__value_PR {
	NRPPA_ResourceSetType_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_ResourceSetType_ExtIEs__value_PR;
typedef enum NRPPA_ResourceType_ExtIEs__value_PR {
	NRPPA_ResourceType_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_ResourceType_ExtIEs__value_PR;
typedef enum NRPPA_ResourceTypePos_ExtIEs__value_PR {
	NRPPA_ResourceTypePos_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_ResourceTypePos_ExtIEs__value_PR;
typedef enum NRPPA_SpatialInformationPos_ExtIEs__value_PR {
	NRPPA_SpatialInformationPos_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_SpatialInformationPos_ExtIEs__value_PR;
typedef enum NRPPA_TimeStampSlotIndex_ExtIEs__value_PR {
	NRPPA_TimeStampSlotIndex_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TimeStampSlotIndex_ExtIEs__value_PR;
typedef enum NRPPA_TransmissionComb_ExtIEs__value_PR {
	NRPPA_TransmissionComb_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TransmissionComb_ExtIEs__value_PR;
typedef enum NRPPA_TransmissionCombPos_ExtIEs__value_PR {
	NRPPA_TransmissionCombPos_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TransmissionCombPos_ExtIEs__value_PR;
typedef enum NRPPA_TrpMeasuredResultsValue_ExtIEs__value_PR {
	NRPPA_TrpMeasuredResultsValue_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TrpMeasuredResultsValue_ExtIEs__value_PR;
typedef enum NRPPA_TrpMeasurementQuality_ExtIEs__value_PR {
	NRPPA_TrpMeasurementQuality_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TrpMeasurementQuality_ExtIEs__value_PR;
typedef enum NRPPA_TRPInformationItem_ExtIEs__value_PR {
	NRPPA_TRPInformationItem_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TRPInformationItem_ExtIEs__value_PR;
typedef enum NRPPA_TRPPositionDefinitionType_ExtIEs__value_PR {
	NRPPA_TRPPositionDefinitionType_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TRPPositionDefinitionType_ExtIEs__value_PR;
typedef enum NRPPA_TRPPositionDirectAccuracy_ExtIEs__value_PR {
	NRPPA_TRPPositionDirectAccuracy_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TRPPositionDirectAccuracy_ExtIEs__value_PR;
typedef enum NRPPA_TRPReferencePointType_ExtIEs__value_PR {
	NRPPA_TRPReferencePointType_ExtIEs__value_PR_NOTHING	/* No components present */
	
} NRPPA_TRPReferencePointType_ExtIEs__value_PR;
typedef enum NRPPA_WLANMeasurementQuantities_ItemIEs__value_PR {
	NRPPA_WLANMeasurementQuantities_ItemIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_WLANMeasurementQuantities_ItemIEs__value_PR_WLANMeasurementQuantities_Item
} NRPPA_WLANMeasurementQuantities_ItemIEs__value_PR;
typedef enum NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR {
	NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR_UE_Measurement_ID,
	NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR_ReportCharacteristics,
	NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR_MeasurementPeriodicity,
	NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR_MeasurementQuantities,
	NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR_OtherRATMeasurementQuantities,
	NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR_WLANMeasurementQuantities
} NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR;
typedef enum NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR {
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_UE_Measurement_ID,
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_UE_Measurement_ID_1,
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_E_CID_MeasurementResult,
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_CriticalityDiagnostics,
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_Cell_Portion_ID,
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_OtherRATMeasurementResult,
	NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR_WLANMeasurementResult
} NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR;
typedef enum NRPPA_E_CIDMeasurementInitiationFailure_IEs__value_PR {
	NRPPA_E_CIDMeasurementInitiationFailure_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_E_CIDMeasurementInitiationFailure_IEs__value_PR_UE_Measurement_ID,
	NRPPA_E_CIDMeasurementInitiationFailure_IEs__value_PR_Cause,
	NRPPA_E_CIDMeasurementInitiationFailure_IEs__value_PR_CriticalityDiagnostics
} NRPPA_E_CIDMeasurementInitiationFailure_IEs__value_PR;
typedef enum NRPPA_E_CIDMeasurementFailureIndication_IEs__value_PR {
	NRPPA_E_CIDMeasurementFailureIndication_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_E_CIDMeasurementFailureIndication_IEs__value_PR_UE_Measurement_ID,
	NRPPA_E_CIDMeasurementFailureIndication_IEs__value_PR_UE_Measurement_ID_1,
	NRPPA_E_CIDMeasurementFailureIndication_IEs__value_PR_Cause
} NRPPA_E_CIDMeasurementFailureIndication_IEs__value_PR;
typedef enum NRPPA_E_CIDMeasurementReport_IEs__value_PR {
	NRPPA_E_CIDMeasurementReport_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_E_CIDMeasurementReport_IEs__value_PR_UE_Measurement_ID,
	NRPPA_E_CIDMeasurementReport_IEs__value_PR_UE_Measurement_ID_1,
	NRPPA_E_CIDMeasurementReport_IEs__value_PR_E_CID_MeasurementResult,
	NRPPA_E_CIDMeasurementReport_IEs__value_PR_Cell_Portion_ID
} NRPPA_E_CIDMeasurementReport_IEs__value_PR;
typedef enum NRPPA_E_CIDMeasurementTerminationCommand_IEs__value_PR {
	NRPPA_E_CIDMeasurementTerminationCommand_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_E_CIDMeasurementTerminationCommand_IEs__value_PR_UE_Measurement_ID,
	NRPPA_E_CIDMeasurementTerminationCommand_IEs__value_PR_UE_Measurement_ID_1
} NRPPA_E_CIDMeasurementTerminationCommand_IEs__value_PR;
typedef enum NRPPA_OTDOAInformationRequest_IEs__value_PR {
	NRPPA_OTDOAInformationRequest_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_OTDOAInformationRequest_IEs__value_PR_OTDOA_Information_Type
} NRPPA_OTDOAInformationRequest_IEs__value_PR;
typedef enum NRPPA_OTDOAInformationResponse_IEs__value_PR {
	NRPPA_OTDOAInformationResponse_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_OTDOAInformationResponse_IEs__value_PR_OTDOACells,
	NRPPA_OTDOAInformationResponse_IEs__value_PR_CriticalityDiagnostics
} NRPPA_OTDOAInformationResponse_IEs__value_PR;
typedef enum NRPPA_OTDOAInformationFailure_IEs__value_PR {
	NRPPA_OTDOAInformationFailure_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_OTDOAInformationFailure_IEs__value_PR_Cause,
	NRPPA_OTDOAInformationFailure_IEs__value_PR_CriticalityDiagnostics
} NRPPA_OTDOAInformationFailure_IEs__value_PR;
typedef enum NRPPA_AssistanceInformationControl_IEs__value_PR {
	NRPPA_AssistanceInformationControl_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_AssistanceInformationControl_IEs__value_PR_Assistance_Information,
	NRPPA_AssistanceInformationControl_IEs__value_PR_Broadcast,
	NRPPA_AssistanceInformationControl_IEs__value_PR_PositioningBroadcastCells
} NRPPA_AssistanceInformationControl_IEs__value_PR;
typedef enum NRPPA_AssistanceInformationFeedback_IEs__value_PR {
	NRPPA_AssistanceInformationFeedback_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_AssistanceInformationFeedback_IEs__value_PR_AssistanceInformationFailureList,
	NRPPA_AssistanceInformationFeedback_IEs__value_PR_PositioningBroadcastCells,
	NRPPA_AssistanceInformationFeedback_IEs__value_PR_CriticalityDiagnostics
} NRPPA_AssistanceInformationFeedback_IEs__value_PR;
typedef enum NRPPA_ErrorIndication_IEs__value_PR {
	NRPPA_ErrorIndication_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_ErrorIndication_IEs__value_PR_Cause,
	NRPPA_ErrorIndication_IEs__value_PR_CriticalityDiagnostics
} NRPPA_ErrorIndication_IEs__value_PR;
typedef enum NRPPA_PositioningInformationRequest_IEs__value_PR {
	NRPPA_PositioningInformationRequest_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningInformationRequest_IEs__value_PR_RequestedSRSTransmissionCharacteristics
} NRPPA_PositioningInformationRequest_IEs__value_PR;
typedef enum NRPPA_PositioningInformationResponse_IEs__value_PR {
	NRPPA_PositioningInformationResponse_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningInformationResponse_IEs__value_PR_SRSConfiguration,
	NRPPA_PositioningInformationResponse_IEs__value_PR_SFNInitialisationTime,
	NRPPA_PositioningInformationResponse_IEs__value_PR_CriticalityDiagnostics
} NRPPA_PositioningInformationResponse_IEs__value_PR;
typedef enum NRPPA_PositioningInformationFailure_IEs__value_PR {
	NRPPA_PositioningInformationFailure_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningInformationFailure_IEs__value_PR_Cause,
	NRPPA_PositioningInformationFailure_IEs__value_PR_CriticalityDiagnostics
} NRPPA_PositioningInformationFailure_IEs__value_PR;
typedef enum NRPPA_PositioningInformationUpdate_IEs__value_PR {
	NRPPA_PositioningInformationUpdate_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningInformationUpdate_IEs__value_PR_SRSConfiguration,
	NRPPA_PositioningInformationUpdate_IEs__value_PR_SFNInitialisationTime
} NRPPA_PositioningInformationUpdate_IEs__value_PR;
typedef enum NRPPA_MeasurementRequest_IEs__value_PR {
	NRPPA_MeasurementRequest_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementRequest_IEs__value_PR_Measurement_ID,
	NRPPA_MeasurementRequest_IEs__value_PR_TRP_MeasurementRequestList,
	NRPPA_MeasurementRequest_IEs__value_PR_ReportCharacteristics,
	NRPPA_MeasurementRequest_IEs__value_PR_MeasurementPeriodicity,
	NRPPA_MeasurementRequest_IEs__value_PR_TRPMeasurementQuantities,
	NRPPA_MeasurementRequest_IEs__value_PR_SRSConfiguration,
	NRPPA_MeasurementRequest_IEs__value_PR_SFNInitialisationTime,
	NRPPA_MeasurementRequest_IEs__value_PR_MeasurementBeamInfoRequest,
	NRPPA_MeasurementRequest_IEs__value_PR_SystemFrameNumber,
	NRPPA_MeasurementRequest_IEs__value_PR_SlotNumber
} NRPPA_MeasurementRequest_IEs__value_PR;
typedef enum NRPPA_MeasurementResponse_IEs__value_PR {
	NRPPA_MeasurementResponse_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementResponse_IEs__value_PR_Measurement_ID,
	NRPPA_MeasurementResponse_IEs__value_PR_Measurement_ID_1,
	NRPPA_MeasurementResponse_IEs__value_PR_TRP_MeasurementResponseList,
	NRPPA_MeasurementResponse_IEs__value_PR_CriticalityDiagnostics
} NRPPA_MeasurementResponse_IEs__value_PR;
typedef enum NRPPA_MeasurementFailure_IEs__value_PR {
	NRPPA_MeasurementFailure_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementFailure_IEs__value_PR_Measurement_ID,
	NRPPA_MeasurementFailure_IEs__value_PR_Cause,
	NRPPA_MeasurementFailure_IEs__value_PR_CriticalityDiagnostics
} NRPPA_MeasurementFailure_IEs__value_PR;
typedef enum NRPPA_MeasurementReport_IEs__value_PR {
	NRPPA_MeasurementReport_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementReport_IEs__value_PR_Measurement_ID,
	NRPPA_MeasurementReport_IEs__value_PR_Measurement_ID_1,
	NRPPA_MeasurementReport_IEs__value_PR_TRP_MeasurementResponseList
} NRPPA_MeasurementReport_IEs__value_PR;
typedef enum NRPPA_MeasurementUpdate_IEs__value_PR {
	NRPPA_MeasurementUpdate_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementUpdate_IEs__value_PR_Measurement_ID,
	NRPPA_MeasurementUpdate_IEs__value_PR_Measurement_ID_1,
	NRPPA_MeasurementUpdate_IEs__value_PR_SRSConfiguration
} NRPPA_MeasurementUpdate_IEs__value_PR;
typedef enum NRPPA_MeasurementAbort_IEs__value_PR {
	NRPPA_MeasurementAbort_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementAbort_IEs__value_PR_Measurement_ID,
	NRPPA_MeasurementAbort_IEs__value_PR_Measurement_ID_1
} NRPPA_MeasurementAbort_IEs__value_PR;
typedef enum NRPPA_MeasurementFailureIndication_IEs__value_PR {
	NRPPA_MeasurementFailureIndication_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_MeasurementFailureIndication_IEs__value_PR_Measurement_ID,
	NRPPA_MeasurementFailureIndication_IEs__value_PR_Measurement_ID_1,
	NRPPA_MeasurementFailureIndication_IEs__value_PR_Cause
} NRPPA_MeasurementFailureIndication_IEs__value_PR;
typedef enum NRPPA_TRPInformationRequest_IEs__value_PR {
	NRPPA_TRPInformationRequest_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_TRPInformationRequest_IEs__value_PR_TRPList,
	NRPPA_TRPInformationRequest_IEs__value_PR_TRPInformationTypeList
} NRPPA_TRPInformationRequest_IEs__value_PR;
typedef enum NRPPA_TRPInformationResponse_IEs__value_PR {
	NRPPA_TRPInformationResponse_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_TRPInformationResponse_IEs__value_PR_TRPInformationList,
	NRPPA_TRPInformationResponse_IEs__value_PR_CriticalityDiagnostics
} NRPPA_TRPInformationResponse_IEs__value_PR;
typedef enum NRPPA_TRPInformationFailure_IEs__value_PR {
	NRPPA_TRPInformationFailure_IEs__value_PR_NOTHING,	/* No components present */
	NRPPA_TRPInformationFailure_IEs__value_PR_Cause,
	NRPPA_TRPInformationFailure_IEs__value_PR_CriticalityDiagnostics
} NRPPA_TRPInformationFailure_IEs__value_PR;
typedef enum NRPPA_PositioningActivationRequestIEs__value_PR {
	NRPPA_PositioningActivationRequestIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningActivationRequestIEs__value_PR_SRSType,
	NRPPA_PositioningActivationRequestIEs__value_PR_ActivationTime
} NRPPA_PositioningActivationRequestIEs__value_PR;
typedef enum NRPPA_PositioningActivationResponseIEs__value_PR {
	NRPPA_PositioningActivationResponseIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningActivationResponseIEs__value_PR_CriticalityDiagnostics,
	NRPPA_PositioningActivationResponseIEs__value_PR_SystemFrameNumber,
	NRPPA_PositioningActivationResponseIEs__value_PR_SlotNumber
} NRPPA_PositioningActivationResponseIEs__value_PR;
typedef enum NRPPA_PositioningActivationFailureIEs__value_PR {
	NRPPA_PositioningActivationFailureIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningActivationFailureIEs__value_PR_Cause,
	NRPPA_PositioningActivationFailureIEs__value_PR_CriticalityDiagnostics
} NRPPA_PositioningActivationFailureIEs__value_PR;
typedef enum NRPPA_PositioningDeactivationIEs__value_PR {
	NRPPA_PositioningDeactivationIEs__value_PR_NOTHING,	/* No components present */
	NRPPA_PositioningDeactivationIEs__value_PR_AbortTransmission
} NRPPA_PositioningDeactivationIEs__value_PR;

/* NRPPA_ProtocolIE-Field */
typedef struct NRPPA_OTDOA_Information_TypeIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_OTDOA_Information_TypeIEs__value {
		NRPPA_OTDOA_Information_TypeIEs__value_PR present;
		union NRPPA_OTDOA_Information_TypeIEs__NRPPA_value_u {
			NRPPA_OTDOA_Information_Type_Item_t	 OTDOA_Information_Type_Item;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OTDOA_Information_TypeIEs_t;
typedef struct NRPPA_SRSType_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_SRSType_ExtIEs__value {
		NRPPA_SRSType_ExtIEs__value_PR present;
		union NRPPA_SRSType_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SRSType_ExtIEs_t;
typedef struct NRPPA_AbortTransmission_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_AbortTransmission_ExtIEs__value {
		NRPPA_AbortTransmission_ExtIEs__value_PR present;
		union NRPPA_AbortTransmission_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_AbortTransmission_ExtIEs_t;
typedef struct NRPPA_Cause_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_Cause_ExtensionIE__value {
		NRPPA_Cause_ExtensionIE__value_PR present;
		union NRPPA_Cause_ExtensionIE__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_Cause_ExtensionIE_t;
typedef struct NRPPA_DL_PRSMutingPattern_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_DL_PRSMutingPattern_ExtIEs__value {
		NRPPA_DL_PRSMutingPattern_ExtIEs__value_PR present;
		union NRPPA_DL_PRSMutingPattern_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_DL_PRSMutingPattern_ExtIEs_t;
typedef struct NRPPA_DL_PRSResourceSetARPLocation_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_DL_PRSResourceSetARPLocation_ExtIEs__value {
		NRPPA_DL_PRSResourceSetARPLocation_ExtIEs__value_PR present;
		union NRPPA_DL_PRSResourceSetARPLocation_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_DL_PRSResourceSetARPLocation_ExtIEs_t;
typedef struct NRPPA_DL_PRSResourceARPLocation_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_DL_PRSResourceARPLocation_ExtIEs__value {
		NRPPA_DL_PRSResourceARPLocation_ExtIEs__value_PR present;
		union NRPPA_DL_PRSResourceARPLocation_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_DL_PRSResourceARPLocation_ExtIEs_t;
typedef struct NRPPA_GNBRxTxTimeDiffMeas_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_GNBRxTxTimeDiffMeas_ExtIEs__value {
		NRPPA_GNBRxTxTimeDiffMeas_ExtIEs__value_PR present;
		union NRPPA_GNBRxTxTimeDiffMeas_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_GNBRxTxTimeDiffMeas_ExtIEs_t;
typedef struct NRPPA_MeasurementQuantities_ItemIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementQuantities_ItemIEs__value {
		NRPPA_MeasurementQuantities_ItemIEs__value_PR present;
		union NRPPA_MeasurementQuantities_ItemIEs__NRPPA_value_u {
			NRPPA_MeasurementQuantities_Item_t	 MeasurementQuantities_Item;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementQuantities_ItemIEs_t;
typedef struct NRPPA_MeasuredResultsValue_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasuredResultsValue_ExtensionIE__value {
		NRPPA_MeasuredResultsValue_ExtensionIE__value_PR present;
		union NRPPA_MeasuredResultsValue_ExtensionIE__NRPPA_value_u {
			NRPPA_ResultSS_RSRP_t	 ResultSS_RSRP;
			NRPPA_ResultSS_RSRQ_t	 ResultSS_RSRQ;
			NRPPA_ResultCSI_RSRP_t	 ResultCSI_RSRP;
			NRPPA_ResultCSI_RSRQ_t	 ResultCSI_RSRQ;
			NRPPA_UL_AoA_t	 UL_AoA;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasuredResultsValue_ExtensionIE_t;
typedef struct NRPPA_NG_RANCell_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_NG_RANCell_ExtensionIE__value {
		NRPPA_NG_RANCell_ExtensionIE__value_PR present;
		union NRPPA_NG_RANCell_ExtensionIE__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_NG_RANCell_ExtensionIE_t;
typedef struct NRPPA_OTDOACell_Information_Item_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_OTDOACell_Information_Item_ExtensionIE__value {
		NRPPA_OTDOACell_Information_Item_ExtensionIE__value_PR present;
		union NRPPA_OTDOACell_Information_Item_ExtensionIE__NRPPA_value_u {
			NRPPA_TDD_Config_EUTRA_Item_t	 TDD_Config_EUTRA_Item;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OTDOACell_Information_Item_ExtensionIE_t;
typedef struct NRPPA_OtherRATMeasurementQuantities_ItemIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_OtherRATMeasurementQuantities_ItemIEs__value {
		NRPPA_OtherRATMeasurementQuantities_ItemIEs__value_PR present;
		union NRPPA_OtherRATMeasurementQuantities_ItemIEs__NRPPA_value_u {
			NRPPA_OtherRATMeasurementQuantities_Item_t	 OtherRATMeasurementQuantities_Item;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OtherRATMeasurementQuantities_ItemIEs_t;
typedef struct NRPPA_OtherRATMeasuredResultsValue_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__value {
		NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__value_PR present;
		union NRPPA_OtherRATMeasuredResultsValue_ExtensionIE__NRPPA_value_u {
			NRPPA_ResultNR_t	 ResultNR;
			NRPPA_ResultEUTRA_t	 ResultEUTRA;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OtherRATMeasuredResultsValue_ExtensionIE_t;
typedef struct NRPPA_PathlossReferenceSignal_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PathlossReferenceSignal_ExtensionIE__value {
		NRPPA_PathlossReferenceSignal_ExtensionIE__value_PR present;
		union NRPPA_PathlossReferenceSignal_ExtensionIE__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PathlossReferenceSignal_ExtensionIE_t;
typedef struct NRPPA_PosResourceSetType_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PosResourceSetType_ExtIEs__value {
		NRPPA_PosResourceSetType_ExtIEs__value_PR present;
		union NRPPA_PosResourceSetType_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PosResourceSetType_ExtIEs_t;
typedef struct NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE__value {
		NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR present;
		union NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE_t;
typedef struct NRPPA_ReferenceSignal_ExtensionIE {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_ReferenceSignal_ExtensionIE__value {
		NRPPA_ReferenceSignal_ExtensionIE__value_PR present;
		union NRPPA_ReferenceSignal_ExtensionIE__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ReferenceSignal_ExtensionIE_t;
typedef struct NRPPA_ReferencePoint_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_ReferencePoint_ExtIEs__value {
		NRPPA_ReferencePoint_ExtIEs__value_PR present;
		union NRPPA_ReferencePoint_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ReferencePoint_ExtIEs_t;
typedef struct NRPPA_ResourceSetType_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_ResourceSetType_ExtIEs__value {
		NRPPA_ResourceSetType_ExtIEs__value_PR present;
		union NRPPA_ResourceSetType_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResourceSetType_ExtIEs_t;
typedef struct NRPPA_ResourceType_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_ResourceType_ExtIEs__value {
		NRPPA_ResourceType_ExtIEs__value_PR present;
		union NRPPA_ResourceType_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResourceType_ExtIEs_t;
typedef struct NRPPA_ResourceTypePos_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_ResourceTypePos_ExtIEs__value {
		NRPPA_ResourceTypePos_ExtIEs__value_PR present;
		union NRPPA_ResourceTypePos_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResourceTypePos_ExtIEs_t;
typedef struct NRPPA_SpatialInformationPos_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_SpatialInformationPos_ExtIEs__value {
		NRPPA_SpatialInformationPos_ExtIEs__value_PR present;
		union NRPPA_SpatialInformationPos_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SpatialInformationPos_ExtIEs_t;
typedef struct NRPPA_TimeStampSlotIndex_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TimeStampSlotIndex_ExtIEs__value {
		NRPPA_TimeStampSlotIndex_ExtIEs__value_PR present;
		union NRPPA_TimeStampSlotIndex_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TimeStampSlotIndex_ExtIEs_t;
typedef struct NRPPA_TransmissionComb_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TransmissionComb_ExtIEs__value {
		NRPPA_TransmissionComb_ExtIEs__value_PR present;
		union NRPPA_TransmissionComb_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TransmissionComb_ExtIEs_t;
typedef struct NRPPA_TransmissionCombPos_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TransmissionCombPos_ExtIEs__value {
		NRPPA_TransmissionCombPos_ExtIEs__value_PR present;
		union NRPPA_TransmissionCombPos_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TransmissionCombPos_ExtIEs_t;
typedef struct NRPPA_TrpMeasuredResultsValue_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TrpMeasuredResultsValue_ExtIEs__value {
		NRPPA_TrpMeasuredResultsValue_ExtIEs__value_PR present;
		union NRPPA_TrpMeasuredResultsValue_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TrpMeasuredResultsValue_ExtIEs_t;
typedef struct NRPPA_TrpMeasurementQuality_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TrpMeasurementQuality_ExtIEs__value {
		NRPPA_TrpMeasurementQuality_ExtIEs__value_PR present;
		union NRPPA_TrpMeasurementQuality_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TrpMeasurementQuality_ExtIEs_t;
typedef struct NRPPA_TRPInformationItem_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TRPInformationItem_ExtIEs__value {
		NRPPA_TRPInformationItem_ExtIEs__value_PR present;
		union NRPPA_TRPInformationItem_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPInformationItem_ExtIEs_t;
typedef struct NRPPA_TRPPositionDefinitionType_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TRPPositionDefinitionType_ExtIEs__value {
		NRPPA_TRPPositionDefinitionType_ExtIEs__value_PR present;
		union NRPPA_TRPPositionDefinitionType_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPPositionDefinitionType_ExtIEs_t;
typedef struct NRPPA_TRPPositionDirectAccuracy_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TRPPositionDirectAccuracy_ExtIEs__value {
		NRPPA_TRPPositionDirectAccuracy_ExtIEs__value_PR present;
		union NRPPA_TRPPositionDirectAccuracy_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPPositionDirectAccuracy_ExtIEs_t;
typedef struct NRPPA_TRPReferencePointType_ExtIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TRPReferencePointType_ExtIEs__value {
		NRPPA_TRPReferencePointType_ExtIEs__value_PR present;
		union NRPPA_TRPReferencePointType_ExtIEs__NRPPA_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPReferencePointType_ExtIEs_t;
typedef struct NRPPA_WLANMeasurementQuantities_ItemIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_WLANMeasurementQuantities_ItemIEs__value {
		NRPPA_WLANMeasurementQuantities_ItemIEs__value_PR present;
		union NRPPA_WLANMeasurementQuantities_ItemIEs__NRPPA_value_u {
			NRPPA_WLANMeasurementQuantities_Item_t	 WLANMeasurementQuantities_Item;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_WLANMeasurementQuantities_ItemIEs_t;
typedef struct NRPPA_E_CIDMeasurementInitiationRequest_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_E_CIDMeasurementInitiationRequest_IEs__value {
		NRPPA_E_CIDMeasurementInitiationRequest_IEs__value_PR present;
		union NRPPA_E_CIDMeasurementInitiationRequest_IEs__NRPPA_value_u {
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID;
			NRPPA_ReportCharacteristics_t	 ReportCharacteristics;
			NRPPA_MeasurementPeriodicity_t	 MeasurementPeriodicity;
			NRPPA_MeasurementQuantities_t	 MeasurementQuantities;
			NRPPA_OtherRATMeasurementQuantities_t	 OtherRATMeasurementQuantities;
			NRPPA_WLANMeasurementQuantities_t	 WLANMeasurementQuantities;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_E_CIDMeasurementInitiationRequest_IEs_t;
typedef struct NRPPA_E_CIDMeasurementInitiationResponse_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_E_CIDMeasurementInitiationResponse_IEs__value {
		NRPPA_E_CIDMeasurementInitiationResponse_IEs__value_PR present;
		union NRPPA_E_CIDMeasurementInitiationResponse_IEs__NRPPA_value_u {
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID;
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID_1;
			NRPPA_E_CID_MeasurementResult_t	 E_CID_MeasurementResult;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
			NRPPA_Cell_Portion_ID_t	 Cell_Portion_ID;
			NRPPA_OtherRATMeasurementResult_t	 OtherRATMeasurementResult;
			NRPPA_WLANMeasurementResult_t	 WLANMeasurementResult;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_E_CIDMeasurementInitiationResponse_IEs_t;
typedef struct NRPPA_E_CIDMeasurementInitiationFailure_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_E_CIDMeasurementInitiationFailure_IEs__value {
		NRPPA_E_CIDMeasurementInitiationFailure_IEs__value_PR present;
		union NRPPA_E_CIDMeasurementInitiationFailure_IEs__NRPPA_value_u {
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID;
			NRPPA_Cause_t	 Cause;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_E_CIDMeasurementInitiationFailure_IEs_t;
typedef struct NRPPA_E_CIDMeasurementFailureIndication_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_E_CIDMeasurementFailureIndication_IEs__value {
		NRPPA_E_CIDMeasurementFailureIndication_IEs__value_PR present;
		union NRPPA_E_CIDMeasurementFailureIndication_IEs__NRPPA_value_u {
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID;
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID_1;
			NRPPA_Cause_t	 Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_E_CIDMeasurementFailureIndication_IEs_t;
typedef struct NRPPA_E_CIDMeasurementReport_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_E_CIDMeasurementReport_IEs__value {
		NRPPA_E_CIDMeasurementReport_IEs__value_PR present;
		union NRPPA_E_CIDMeasurementReport_IEs__NRPPA_value_u {
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID;
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID_1;
			NRPPA_E_CID_MeasurementResult_t	 E_CID_MeasurementResult;
			NRPPA_Cell_Portion_ID_t	 Cell_Portion_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_E_CIDMeasurementReport_IEs_t;
typedef struct NRPPA_E_CIDMeasurementTerminationCommand_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_E_CIDMeasurementTerminationCommand_IEs__value {
		NRPPA_E_CIDMeasurementTerminationCommand_IEs__value_PR present;
		union NRPPA_E_CIDMeasurementTerminationCommand_IEs__NRPPA_value_u {
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID;
			NRPPA_UE_Measurement_ID_t	 UE_Measurement_ID_1;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_E_CIDMeasurementTerminationCommand_IEs_t;
typedef struct NRPPA_OTDOAInformationRequest_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_OTDOAInformationRequest_IEs__value {
		NRPPA_OTDOAInformationRequest_IEs__value_PR present;
		union NRPPA_OTDOAInformationRequest_IEs__NRPPA_value_u {
			NRPPA_OTDOA_Information_Type_t	 OTDOA_Information_Type;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OTDOAInformationRequest_IEs_t;
typedef struct NRPPA_OTDOAInformationResponse_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_OTDOAInformationResponse_IEs__value {
		NRPPA_OTDOAInformationResponse_IEs__value_PR present;
		union NRPPA_OTDOAInformationResponse_IEs__NRPPA_value_u {
			NRPPA_OTDOACells_t	 OTDOACells;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OTDOAInformationResponse_IEs_t;
typedef struct NRPPA_OTDOAInformationFailure_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_OTDOAInformationFailure_IEs__value {
		NRPPA_OTDOAInformationFailure_IEs__value_PR present;
		union NRPPA_OTDOAInformationFailure_IEs__NRPPA_value_u {
			NRPPA_Cause_t	 Cause;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OTDOAInformationFailure_IEs_t;
typedef struct NRPPA_AssistanceInformationControl_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_AssistanceInformationControl_IEs__value {
		NRPPA_AssistanceInformationControl_IEs__value_PR present;
		union NRPPA_AssistanceInformationControl_IEs__NRPPA_value_u {
			NRPPA_Assistance_Information_t	 Assistance_Information;
			NRPPA_Broadcast_t	 Broadcast;
			NRPPA_PositioningBroadcastCells_t	 PositioningBroadcastCells;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_AssistanceInformationControl_IEs_t;
typedef struct NRPPA_AssistanceInformationFeedback_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_AssistanceInformationFeedback_IEs__value {
		NRPPA_AssistanceInformationFeedback_IEs__value_PR present;
		union NRPPA_AssistanceInformationFeedback_IEs__NRPPA_value_u {
			NRPPA_AssistanceInformationFailureList_t	 AssistanceInformationFailureList;
			NRPPA_PositioningBroadcastCells_t	 PositioningBroadcastCells;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_AssistanceInformationFeedback_IEs_t;
typedef struct NRPPA_ErrorIndication_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_ErrorIndication_IEs__value {
		NRPPA_ErrorIndication_IEs__value_PR present;
		union NRPPA_ErrorIndication_IEs__NRPPA_value_u {
			NRPPA_Cause_t	 Cause;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ErrorIndication_IEs_t;
typedef struct NRPPA_PositioningInformationRequest_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningInformationRequest_IEs__value {
		NRPPA_PositioningInformationRequest_IEs__value_PR present;
		union NRPPA_PositioningInformationRequest_IEs__NRPPA_value_u {
			NRPPA_RequestedSRSTransmissionCharacteristics_t	 RequestedSRSTransmissionCharacteristics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningInformationRequest_IEs_t;
typedef struct NRPPA_PositioningInformationResponse_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningInformationResponse_IEs__value {
		NRPPA_PositioningInformationResponse_IEs__value_PR present;
		union NRPPA_PositioningInformationResponse_IEs__NRPPA_value_u {
			NRPPA_SRSConfiguration_t	 SRSConfiguration;
			NRPPA_SFNInitialisationTime_t	 SFNInitialisationTime;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningInformationResponse_IEs_t;
typedef struct NRPPA_PositioningInformationFailure_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningInformationFailure_IEs__value {
		NRPPA_PositioningInformationFailure_IEs__value_PR present;
		union NRPPA_PositioningInformationFailure_IEs__NRPPA_value_u {
			NRPPA_Cause_t	 Cause;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningInformationFailure_IEs_t;
typedef struct NRPPA_PositioningInformationUpdate_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningInformationUpdate_IEs__value {
		NRPPA_PositioningInformationUpdate_IEs__value_PR present;
		union NRPPA_PositioningInformationUpdate_IEs__NRPPA_value_u {
			NRPPA_SRSConfiguration_t	 SRSConfiguration;
			NRPPA_SFNInitialisationTime_t	 SFNInitialisationTime;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningInformationUpdate_IEs_t;
typedef struct NRPPA_MeasurementRequest_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementRequest_IEs__value {
		NRPPA_MeasurementRequest_IEs__value_PR present;
		union NRPPA_MeasurementRequest_IEs__NRPPA_value_u {
			NRPPA_Measurement_ID_t	 Measurement_ID;
			NRPPA_TRP_MeasurementRequestList_t	 TRP_MeasurementRequestList;
			NRPPA_ReportCharacteristics_t	 ReportCharacteristics;
			NRPPA_MeasurementPeriodicity_t	 MeasurementPeriodicity;
			NRPPA_TRPMeasurementQuantities_t	 TRPMeasurementQuantities;
			NRPPA_SRSConfiguration_t	 SRSConfiguration;
			NRPPA_SFNInitialisationTime_t	 SFNInitialisationTime;
			NRPPA_MeasurementBeamInfoRequest_t	 MeasurementBeamInfoRequest;
			NRPPA_SystemFrameNumber_t	 SystemFrameNumber;
			NRPPA_SlotNumber_t	 SlotNumber;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementRequest_IEs_t;
typedef struct NRPPA_MeasurementResponse_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementResponse_IEs__value {
		NRPPA_MeasurementResponse_IEs__value_PR present;
		union NRPPA_MeasurementResponse_IEs__NRPPA_value_u {
			NRPPA_Measurement_ID_t	 Measurement_ID;
			NRPPA_Measurement_ID_t	 Measurement_ID_1;
			NRPPA_TRP_MeasurementResponseList_t	 TRP_MeasurementResponseList;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementResponse_IEs_t;
typedef struct NRPPA_MeasurementFailure_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementFailure_IEs__value {
		NRPPA_MeasurementFailure_IEs__value_PR present;
		union NRPPA_MeasurementFailure_IEs__NRPPA_value_u {
			NRPPA_Measurement_ID_t	 Measurement_ID;
			NRPPA_Cause_t	 Cause;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementFailure_IEs_t;
typedef struct NRPPA_MeasurementReport_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementReport_IEs__value {
		NRPPA_MeasurementReport_IEs__value_PR present;
		union NRPPA_MeasurementReport_IEs__NRPPA_value_u {
			NRPPA_Measurement_ID_t	 Measurement_ID;
			NRPPA_Measurement_ID_t	 Measurement_ID_1;
			NRPPA_TRP_MeasurementResponseList_t	 TRP_MeasurementResponseList;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementReport_IEs_t;
typedef struct NRPPA_MeasurementUpdate_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementUpdate_IEs__value {
		NRPPA_MeasurementUpdate_IEs__value_PR present;
		union NRPPA_MeasurementUpdate_IEs__NRPPA_value_u {
			NRPPA_Measurement_ID_t	 Measurement_ID;
			NRPPA_Measurement_ID_t	 Measurement_ID_1;
			NRPPA_SRSConfiguration_t	 SRSConfiguration;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementUpdate_IEs_t;
typedef struct NRPPA_MeasurementAbort_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementAbort_IEs__value {
		NRPPA_MeasurementAbort_IEs__value_PR present;
		union NRPPA_MeasurementAbort_IEs__NRPPA_value_u {
			NRPPA_Measurement_ID_t	 Measurement_ID;
			NRPPA_Measurement_ID_t	 Measurement_ID_1;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementAbort_IEs_t;
typedef struct NRPPA_MeasurementFailureIndication_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_MeasurementFailureIndication_IEs__value {
		NRPPA_MeasurementFailureIndication_IEs__value_PR present;
		union NRPPA_MeasurementFailureIndication_IEs__NRPPA_value_u {
			NRPPA_Measurement_ID_t	 Measurement_ID;
			NRPPA_Measurement_ID_t	 Measurement_ID_1;
			NRPPA_Cause_t	 Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasurementFailureIndication_IEs_t;
typedef struct NRPPA_TRPInformationRequest_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TRPInformationRequest_IEs__value {
		NRPPA_TRPInformationRequest_IEs__value_PR present;
		union NRPPA_TRPInformationRequest_IEs__NRPPA_value_u {
			NRPPA_TRPList_t	 TRPList;
			NRPPA_TRPInformationTypeList_t	 TRPInformationTypeList;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPInformationRequest_IEs_t;
typedef struct NRPPA_TRPInformationResponse_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TRPInformationResponse_IEs__value {
		NRPPA_TRPInformationResponse_IEs__value_PR present;
		union NRPPA_TRPInformationResponse_IEs__NRPPA_value_u {
			NRPPA_TRPInformationList_t	 TRPInformationList;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPInformationResponse_IEs_t;
typedef struct NRPPA_TRPInformationFailure_IEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_TRPInformationFailure_IEs__value {
		NRPPA_TRPInformationFailure_IEs__value_PR present;
		union NRPPA_TRPInformationFailure_IEs__NRPPA_value_u {
			NRPPA_Cause_t	 Cause;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPInformationFailure_IEs_t;
typedef struct NRPPA_PositioningActivationRequestIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningActivationRequestIEs__value {
		NRPPA_PositioningActivationRequestIEs__value_PR present;
		union NRPPA_PositioningActivationRequestIEs__NRPPA_value_u {
			NRPPA_SRSType_t	 SRSType;
			NRPPA_ActivationTime_t	 ActivationTime;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningActivationRequestIEs_t;
typedef struct NRPPA_PositioningActivationResponseIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningActivationResponseIEs__value {
		NRPPA_PositioningActivationResponseIEs__value_PR present;
		union NRPPA_PositioningActivationResponseIEs__NRPPA_value_u {
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
			NRPPA_SystemFrameNumber_t	 SystemFrameNumber;
			NRPPA_SlotNumber_t	 SlotNumber;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningActivationResponseIEs_t;
typedef struct NRPPA_PositioningActivationFailureIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningActivationFailureIEs__value {
		NRPPA_PositioningActivationFailureIEs__value_PR present;
		union NRPPA_PositioningActivationFailureIEs__NRPPA_value_u {
			NRPPA_Cause_t	 Cause;
			NRPPA_CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningActivationFailureIEs_t;
typedef struct NRPPA_PositioningDeactivationIEs {
	NRPPA_ProtocolIE_ID_t	 id;
	NRPPA_Criticality_t	 criticality;
	struct NRPPA_PositioningDeactivationIEs__value {
		NRPPA_PositioningDeactivationIEs__value_PR present;
		union NRPPA_PositioningDeactivationIEs__NRPPA_value_u {
			NRPPA_AbortTransmission_t	 AbortTransmission;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningDeactivationIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OTDOA_Information_TypeIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_OTDOA_Information_TypeIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_OTDOA_Information_TypeIEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SRSType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_SRSType_ExtIEs_specs_5;
extern asn_TYPE_member_t asn_MBR_NRPPA_SRSType_ExtIEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_AbortTransmission_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_AbortTransmission_ExtIEs_specs_9;
extern asn_TYPE_member_t asn_MBR_NRPPA_AbortTransmission_ExtIEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_Cause_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_Cause_ExtensionIE_specs_13;
extern asn_TYPE_member_t asn_MBR_NRPPA_Cause_ExtensionIE_13[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_DL_PRSMutingPattern_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_DL_PRSMutingPattern_ExtIEs_specs_17;
extern asn_TYPE_member_t asn_MBR_NRPPA_DL_PRSMutingPattern_ExtIEs_17[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_DL_PRSResourceSetARPLocation_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_DL_PRSResourceSetARPLocation_ExtIEs_specs_21;
extern asn_TYPE_member_t asn_MBR_NRPPA_DL_PRSResourceSetARPLocation_ExtIEs_21[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_DL_PRSResourceARPLocation_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_DL_PRSResourceARPLocation_ExtIEs_specs_25;
extern asn_TYPE_member_t asn_MBR_NRPPA_DL_PRSResourceARPLocation_ExtIEs_25[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_GNBRxTxTimeDiffMeas_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_GNBRxTxTimeDiffMeas_ExtIEs_specs_29;
extern asn_TYPE_member_t asn_MBR_NRPPA_GNBRxTxTimeDiffMeas_ExtIEs_29[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementQuantities_ItemIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementQuantities_ItemIEs_specs_33;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementQuantities_ItemIEs_33[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasuredResultsValue_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasuredResultsValue_ExtensionIE_specs_37;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasuredResultsValue_ExtensionIE_37[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_NG_RANCell_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_NG_RANCell_ExtensionIE_specs_41;
extern asn_TYPE_member_t asn_MBR_NRPPA_NG_RANCell_ExtensionIE_41[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OTDOACell_Information_Item_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_OTDOACell_Information_Item_ExtensionIE_specs_45;
extern asn_TYPE_member_t asn_MBR_NRPPA_OTDOACell_Information_Item_ExtensionIE_45[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OtherRATMeasurementQuantities_ItemIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_OtherRATMeasurementQuantities_ItemIEs_specs_49;
extern asn_TYPE_member_t asn_MBR_NRPPA_OtherRATMeasurementQuantities_ItemIEs_49[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OtherRATMeasuredResultsValue_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_OtherRATMeasuredResultsValue_ExtensionIE_specs_53;
extern asn_TYPE_member_t asn_MBR_NRPPA_OtherRATMeasuredResultsValue_ExtensionIE_53[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PathlossReferenceSignal_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PathlossReferenceSignal_ExtensionIE_specs_57;
extern asn_TYPE_member_t asn_MBR_NRPPA_PathlossReferenceSignal_ExtensionIE_57[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PosResourceSetType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PosResourceSetType_ExtIEs_specs_61;
extern asn_TYPE_member_t asn_MBR_NRPPA_PosResourceSetType_ExtIEs_61[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE_specs_65;
extern asn_TYPE_member_t asn_MBR_NRPPA_PRSMutingConfiguration_EUTRA_ExtensionIE_65[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ReferenceSignal_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ReferenceSignal_ExtensionIE_specs_69;
extern asn_TYPE_member_t asn_MBR_NRPPA_ReferenceSignal_ExtensionIE_69[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ReferencePoint_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ReferencePoint_ExtIEs_specs_73;
extern asn_TYPE_member_t asn_MBR_NRPPA_ReferencePoint_ExtIEs_73[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResourceSetType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResourceSetType_ExtIEs_specs_77;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResourceSetType_ExtIEs_77[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResourceType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResourceType_ExtIEs_specs_81;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResourceType_ExtIEs_81[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResourceTypePos_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResourceTypePos_ExtIEs_specs_85;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResourceTypePos_ExtIEs_85[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SpatialInformationPos_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_SpatialInformationPos_ExtIEs_specs_89;
extern asn_TYPE_member_t asn_MBR_NRPPA_SpatialInformationPos_ExtIEs_89[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TimeStampSlotIndex_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TimeStampSlotIndex_ExtIEs_specs_93;
extern asn_TYPE_member_t asn_MBR_NRPPA_TimeStampSlotIndex_ExtIEs_93[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TransmissionComb_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TransmissionComb_ExtIEs_specs_97;
extern asn_TYPE_member_t asn_MBR_NRPPA_TransmissionComb_ExtIEs_97[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TransmissionCombPos_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TransmissionCombPos_ExtIEs_specs_101;
extern asn_TYPE_member_t asn_MBR_NRPPA_TransmissionCombPos_ExtIEs_101[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TrpMeasuredResultsValue_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TrpMeasuredResultsValue_ExtIEs_specs_105;
extern asn_TYPE_member_t asn_MBR_NRPPA_TrpMeasuredResultsValue_ExtIEs_105[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TrpMeasurementQuality_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TrpMeasurementQuality_ExtIEs_specs_109;
extern asn_TYPE_member_t asn_MBR_NRPPA_TrpMeasurementQuality_ExtIEs_109[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPInformationItem_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRPInformationItem_ExtIEs_specs_113;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPInformationItem_ExtIEs_113[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPPositionDefinitionType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRPPositionDefinitionType_ExtIEs_specs_117;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPPositionDefinitionType_ExtIEs_117[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPPositionDirectAccuracy_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRPPositionDirectAccuracy_ExtIEs_specs_121;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPPositionDirectAccuracy_ExtIEs_121[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPReferencePointType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRPReferencePointType_ExtIEs_specs_125;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPReferencePointType_ExtIEs_125[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_WLANMeasurementQuantities_ItemIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_WLANMeasurementQuantities_ItemIEs_specs_129;
extern asn_TYPE_member_t asn_MBR_NRPPA_WLANMeasurementQuantities_ItemIEs_129[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_E_CIDMeasurementInitiationRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_E_CIDMeasurementInitiationRequest_IEs_specs_133;
extern asn_TYPE_member_t asn_MBR_NRPPA_E_CIDMeasurementInitiationRequest_IEs_133[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_E_CIDMeasurementInitiationResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_E_CIDMeasurementInitiationResponse_IEs_specs_137;
extern asn_TYPE_member_t asn_MBR_NRPPA_E_CIDMeasurementInitiationResponse_IEs_137[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_E_CIDMeasurementInitiationFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_E_CIDMeasurementInitiationFailure_IEs_specs_141;
extern asn_TYPE_member_t asn_MBR_NRPPA_E_CIDMeasurementInitiationFailure_IEs_141[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_E_CIDMeasurementFailureIndication_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_E_CIDMeasurementFailureIndication_IEs_specs_145;
extern asn_TYPE_member_t asn_MBR_NRPPA_E_CIDMeasurementFailureIndication_IEs_145[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_E_CIDMeasurementReport_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_E_CIDMeasurementReport_IEs_specs_149;
extern asn_TYPE_member_t asn_MBR_NRPPA_E_CIDMeasurementReport_IEs_149[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_E_CIDMeasurementTerminationCommand_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_E_CIDMeasurementTerminationCommand_IEs_specs_153;
extern asn_TYPE_member_t asn_MBR_NRPPA_E_CIDMeasurementTerminationCommand_IEs_153[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OTDOAInformationRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_OTDOAInformationRequest_IEs_specs_157;
extern asn_TYPE_member_t asn_MBR_NRPPA_OTDOAInformationRequest_IEs_157[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OTDOAInformationResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_OTDOAInformationResponse_IEs_specs_161;
extern asn_TYPE_member_t asn_MBR_NRPPA_OTDOAInformationResponse_IEs_161[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OTDOAInformationFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_OTDOAInformationFailure_IEs_specs_165;
extern asn_TYPE_member_t asn_MBR_NRPPA_OTDOAInformationFailure_IEs_165[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_AssistanceInformationControl_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_AssistanceInformationControl_IEs_specs_169;
extern asn_TYPE_member_t asn_MBR_NRPPA_AssistanceInformationControl_IEs_169[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_AssistanceInformationFeedback_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_AssistanceInformationFeedback_IEs_specs_173;
extern asn_TYPE_member_t asn_MBR_NRPPA_AssistanceInformationFeedback_IEs_173[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ErrorIndication_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ErrorIndication_IEs_specs_177;
extern asn_TYPE_member_t asn_MBR_NRPPA_ErrorIndication_IEs_177[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningInformationRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningInformationRequest_IEs_specs_181;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningInformationRequest_IEs_181[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningInformationResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningInformationResponse_IEs_specs_185;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningInformationResponse_IEs_185[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningInformationFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningInformationFailure_IEs_specs_189;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningInformationFailure_IEs_189[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningInformationUpdate_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningInformationUpdate_IEs_specs_193;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningInformationUpdate_IEs_193[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementRequest_IEs_specs_197;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementRequest_IEs_197[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementResponse_IEs_specs_201;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementResponse_IEs_201[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementFailure_IEs_specs_205;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementFailure_IEs_205[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementReport_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementReport_IEs_specs_209;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementReport_IEs_209[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementUpdate_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementUpdate_IEs_specs_213;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementUpdate_IEs_213[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementAbort_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementAbort_IEs_specs_217;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementAbort_IEs_217[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementFailureIndication_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasurementFailureIndication_IEs_specs_221;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasurementFailureIndication_IEs_221[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPInformationRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRPInformationRequest_IEs_specs_225;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPInformationRequest_IEs_225[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPInformationResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRPInformationResponse_IEs_specs_229;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPInformationResponse_IEs_229[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPInformationFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRPInformationFailure_IEs_specs_233;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPInformationFailure_IEs_233[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningActivationRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningActivationRequestIEs_specs_237;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningActivationRequestIEs_237[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningActivationResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningActivationResponseIEs_specs_241;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningActivationResponseIEs_241[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningActivationFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningActivationFailureIEs_specs_245;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningActivationFailureIEs_245[3];
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningDeactivationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningDeactivationIEs_specs_249;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningDeactivationIEs_249[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ProtocolIE_Field_H_ */
#include <asn_internal.h>
