/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_MeasurementPeriodicity_H_
#define	_NRPPA_MeasurementPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_MeasurementPeriodicity {
	NRPPA_MeasurementPeriodicity_ms120	= 0,
	NRPPA_MeasurementPeriodicity_ms240	= 1,
	NRPPA_MeasurementPeriodicity_ms480	= 2,
	NRPPA_MeasurementPeriodicity_ms640	= 3,
	NRPPA_MeasurementPeriodicity_ms1024	= 4,
	NRPPA_MeasurementPeriodicity_ms2048	= 5,
	NRPPA_MeasurementPeriodicity_ms5120	= 6,
	NRPPA_MeasurementPeriodicity_ms10240	= 7,
	NRPPA_MeasurementPeriodicity_min1	= 8,
	NRPPA_MeasurementPeriodicity_min6	= 9,
	NRPPA_MeasurementPeriodicity_min12	= 10,
	NRPPA_MeasurementPeriodicity_min30	= 11,
	NRPPA_MeasurementPeriodicity_min60	= 12
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_MeasurementPeriodicity;

/* NRPPA_MeasurementPeriodicity */
typedef long	 NRPPA_MeasurementPeriodicity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_MeasurementPeriodicity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementPeriodicity;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_MeasurementPeriodicity_specs_1;
asn_struct_free_f NRPPA_MeasurementPeriodicity_free;
asn_struct_print_f NRPPA_MeasurementPeriodicity_print;
asn_constr_check_f NRPPA_MeasurementPeriodicity_constraint;
ber_type_decoder_f NRPPA_MeasurementPeriodicity_decode_ber;
der_type_encoder_f NRPPA_MeasurementPeriodicity_encode_der;
xer_type_decoder_f NRPPA_MeasurementPeriodicity_decode_xer;
xer_type_encoder_f NRPPA_MeasurementPeriodicity_encode_xer;
jer_type_encoder_f NRPPA_MeasurementPeriodicity_encode_jer;
per_type_decoder_f NRPPA_MeasurementPeriodicity_decode_uper;
per_type_encoder_f NRPPA_MeasurementPeriodicity_encode_uper;
per_type_decoder_f NRPPA_MeasurementPeriodicity_decode_aper;
per_type_encoder_f NRPPA_MeasurementPeriodicity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_MeasurementPeriodicity_H_ */
#include <asn_internal.h>
