/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_CriticalityDiagnostics_IE_List_H_
#define	_NRPPA_CriticalityDiagnostics_IE_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "NRPPA_Criticality.h"
#include "NRPPA_ProtocolIE-ID.h"
#include "NRPPA_TypeOfError.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct NRPPA_CriticalityDiagnostics_IE_List__Member {
	NRPPA_Criticality_t	 iECriticality;
	NRPPA_ProtocolIE_ID_t	 iE_ID;
	NRPPA_TypeOfError_t	 typeOfError;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CriticalityDiagnostics_IE_List__Member;

/* NRPPA_CriticalityDiagnostics-IE-List */
typedef struct NRPPA_CriticalityDiagnostics_IE_List {
	A_SEQUENCE_OF(CriticalityDiagnostics_IE_List__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_CriticalityDiagnostics_IE_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_CriticalityDiagnostics_IE_List;
extern asn_SET_OF_specifics_t asn_SPC_NRPPA_CriticalityDiagnostics_IE_List_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_CriticalityDiagnostics_IE_List_1[1];
extern asn_per_constraints_t asn_PER_type_NRPPA_CriticalityDiagnostics_IE_List_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_CriticalityDiagnostics_IE_List_H_ */
#include <asn_internal.h>
