/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_TrpMeasurementAngleQuality_H_
#define	_NRPPA_TrpMeasurementAngleQuality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TrpMeasurementAngleQuality__resolution {
	NRPPA_TrpMeasurementAngleQuality__resolution_deg0dot1	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_TrpMeasurementAngleQuality__resolution;

/* NRPPA_TrpMeasurementAngleQuality */
typedef struct NRPPA_TrpMeasurementAngleQuality {
	long	 azimuthQuality;
	long	*zenithQuality;	/* OPTIONAL */
	long	 resolution;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TrpMeasurementAngleQuality_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_resolution_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TrpMeasurementAngleQuality;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TrpMeasurementAngleQuality_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TrpMeasurementAngleQuality_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TrpMeasurementAngleQuality_H_ */
#include <asn_internal.h>
