/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_TRPPositionDirectAccuracy_H_
#define	_NRPPA_TRPPositionDirectAccuracy_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TRPPositionDirectAccuracy_PR {
	NRPPA_TRPPositionDirectAccuracy_PR_NOTHING,	/* No components present */
	NRPPA_TRPPositionDirectAccuracy_PR_tRPPosition,
	NRPPA_TRPPositionDirectAccuracy_PR_tRPHAposition,
	NRPPA_TRPPositionDirectAccuracy_PR_choice_extension
} NRPPA_TRPPositionDirectAccuracy_PR;

/* Forward declarations */
struct NRPPA_NG_RANAccessPointPosition;
struct NRPPA_NGRANHighAccuracyAccessPointPosition;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_TRPPositionDirectAccuracy */
typedef struct NRPPA_TRPPositionDirectAccuracy {
	NRPPA_TRPPositionDirectAccuracy_PR present;
	union NRPPA_TRPPositionDirectAccuracy_u {
		struct NRPPA_NG_RANAccessPointPosition	*tRPPosition;
		struct NRPPA_NGRANHighAccuracyAccessPointPosition	*tRPHAposition;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPPositionDirectAccuracy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPPositionDirectAccuracy;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_TRPPositionDirectAccuracy_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPPositionDirectAccuracy_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_TRPPositionDirectAccuracy_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TRPPositionDirectAccuracy_H_ */
#include <asn_internal.h>
