/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_TrpMeasuredResultsValue_H_
#define	_NRPPA_TrpMeasuredResultsValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_UL-SRS-RSRP.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TrpMeasuredResultsValue_PR {
	NRPPA_TrpMeasuredResultsValue_PR_NOTHING,	/* No components present */
	NRPPA_TrpMeasuredResultsValue_PR_uL_AngleOfArrival,
	NRPPA_TrpMeasuredResultsValue_PR_uL_SRS_RSRP,
	NRPPA_TrpMeasuredResultsValue_PR_uL_RTOA,
	NRPPA_TrpMeasuredResultsValue_PR_gNB_RxTxTimeDiff,
	NRPPA_TrpMeasuredResultsValue_PR_choice_extension
} NRPPA_TrpMeasuredResultsValue_PR;

/* Forward declarations */
struct NRPPA_UL_AoA;
struct NRPPA_UL_RTOAMeasurement;
struct NRPPA_GNB_RxTxTimeDiff;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_TrpMeasuredResultsValue */
typedef struct NRPPA_TrpMeasuredResultsValue {
	NRPPA_TrpMeasuredResultsValue_PR present;
	union NRPPA_TrpMeasuredResultsValue_u {
		struct NRPPA_UL_AoA	*uL_AngleOfArrival;
		NRPPA_UL_SRS_RSRP_t	 uL_SRS_RSRP;
		struct NRPPA_UL_RTOAMeasurement	*uL_RTOA;
		struct NRPPA_GNB_RxTxTimeDiff	*gNB_RxTxTimeDiff;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TrpMeasuredResultsValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TrpMeasuredResultsValue;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_TrpMeasuredResultsValue_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TrpMeasuredResultsValue_1[5];
extern asn_per_constraints_t asn_PER_type_NRPPA_TrpMeasuredResultsValue_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TrpMeasuredResultsValue_H_ */
#include <asn_internal.h>
