/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Contents"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_SRSType_H_
#define	_NRPPA_SRSType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_SRSType_PR {
	NRPPA_SRSType_PR_NOTHING,	/* No components present */
	NRPPA_SRSType_PR_semipersistentSRS,
	NRPPA_SRSType_PR_aperiodicSRS,
	NRPPA_SRSType_PR_sRSType_extension
} NRPPA_SRSType_PR;

/* Forward declarations */
struct NRPPA_SemipersistentSRS;
struct NRPPA_AperiodicSRS;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_SRSType */
typedef struct NRPPA_SRSType {
	NRPPA_SRSType_PR present;
	union NRPPA_SRSType_u {
		struct NRPPA_SemipersistentSRS	*semipersistentSRS;
		struct NRPPA_AperiodicSRS	*aperiodicSRS;
		struct NRPPA_ProtocolIE_Single_Container	*sRSType_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SRSType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SRSType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_SRSType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_SRSType_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_SRSType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_SRSType_H_ */
#include <asn_internal.h>
