/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_CriticalityDiagnostics_H_
#define	_NRPPA_CriticalityDiagnostics_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_ProcedureCode.h"
#include "NRPPA_TriggeringMessage.h"
#include "NRPPA_Criticality.h"
#include "NRPPA_NRPPATransactionID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_CriticalityDiagnostics_IE_List;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_CriticalityDiagnostics */
typedef struct NRPPA_CriticalityDiagnostics {
	NRPPA_ProcedureCode_t	*procedureCode;	/* OPTIONAL */
	NRPPA_TriggeringMessage_t	*triggeringMessage;	/* OPTIONAL */
	NRPPA_Criticality_t	*procedureCriticality;	/* OPTIONAL */
	NRPPA_NRPPATransactionID_t	*nrppatransactionID;	/* OPTIONAL */
	struct NRPPA_CriticalityDiagnostics_IE_List	*iEsCriticalityDiagnostics;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_CriticalityDiagnostics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_CriticalityDiagnostics;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_CriticalityDiagnostics_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_CriticalityDiagnostics_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_CriticalityDiagnostics_H_ */
#include <asn_internal.h>
