/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_NG_RANCell_H_
#define	_NRPPA_NG_RANCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_EUTRACellIdentifier.h"
#include "NRPPA_NRCellIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_NG_RANCell_PR {
	NRPPA_NG_RANCell_PR_NOTHING,	/* No components present */
	NRPPA_NG_RANCell_PR_eUTRA_CellID,
	NRPPA_NG_RANCell_PR_nR_CellID,
	NRPPA_NG_RANCell_PR_nG_RANCell_Extension
} NRPPA_NG_RANCell_PR;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_NG-RANCell */
typedef struct NRPPA_NG_RANCell {
	NRPPA_NG_RANCell_PR present;
	union NRPPA_NG_RANCell_u {
		NRPPA_EUTRACellIdentifier_t	 eUTRA_CellID;
		NRPPA_NRCellIdentifier_t	 nR_CellID;
		struct NRPPA_ProtocolIE_Single_Container	*nG_RANCell_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_NG_RANCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_NG_RANCell;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_NG_RANCell_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_NG_RANCell_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_NG_RANCell_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_NG_RANCell_H_ */
#include <asn_internal.h>
