/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_DL_PRSResourceSetARPLocation_H_
#define	_NRPPA_DL_PRSResourceSetARPLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_DL_PRSResourceSetARPLocation_PR {
	NRPPA_DL_PRSResourceSetARPLocation_PR_NOTHING,	/* No components present */
	NRPPA_DL_PRSResourceSetARPLocation_PR_relativeGeodeticLocation,
	NRPPA_DL_PRSResourceSetARPLocation_PR_relativeCartesianLocation,
	NRPPA_DL_PRSResourceSetARPLocation_PR_choice_Extension
} NRPPA_DL_PRSResourceSetARPLocation_PR;

/* Forward declarations */
struct NRPPA_RelativeGeodeticLocation;
struct NRPPA_RelativeCartesianLocation;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_DL-PRSResourceSetARPLocation */
typedef struct NRPPA_DL_PRSResourceSetARPLocation {
	NRPPA_DL_PRSResourceSetARPLocation_PR present;
	union NRPPA_DL_PRSResourceSetARPLocation_u {
		struct NRPPA_RelativeGeodeticLocation	*relativeGeodeticLocation;
		struct NRPPA_RelativeCartesianLocation	*relativeCartesianLocation;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_DL_PRSResourceSetARPLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_DL_PRSResourceSetARPLocation;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_DL_PRSResourceSetARPLocation_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_DL_PRSResourceSetARPLocation_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_DL_PRSResourceSetARPLocation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_DL_PRSResourceSetARPLocation_H_ */
#include <asn_internal.h>
