/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_SRSResource_H_
#define	_NRPPA_SRSResource_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_SRSResourceID.h"
#include <NativeEnumerated.h>
#include "NRPPA_TransmissionComb.h"
#include <NativeInteger.h>
#include "NRPPA_ResourceType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_SRSResource__nrofSRS_Ports {
	NRPPA_SRSResource__nrofSRS_Ports_port1	= 0,
	NRPPA_SRSResource__nrofSRS_Ports_ports2	= 1,
	NRPPA_SRSResource__nrofSRS_Ports_ports4	= 2
} e_NRPPA_SRSResource__nrofSRS_Ports;
typedef enum NRPPA_SRSResource__nrofSymbols {
	NRPPA_SRSResource__nrofSymbols_n1	= 0,
	NRPPA_SRSResource__nrofSymbols_n2	= 1,
	NRPPA_SRSResource__nrofSymbols_n4	= 2
} e_NRPPA_SRSResource__nrofSymbols;
typedef enum NRPPA_SRSResource__repetitionFactor {
	NRPPA_SRSResource__repetitionFactor_n1	= 0,
	NRPPA_SRSResource__repetitionFactor_n2	= 1,
	NRPPA_SRSResource__repetitionFactor_n4	= 2
} e_NRPPA_SRSResource__repetitionFactor;
typedef enum NRPPA_SRSResource__groupOrSequenceHopping {
	NRPPA_SRSResource__groupOrSequenceHopping_neither	= 0,
	NRPPA_SRSResource__groupOrSequenceHopping_groupHopping	= 1,
	NRPPA_SRSResource__groupOrSequenceHopping_sequenceHopping	= 2
} e_NRPPA_SRSResource__groupOrSequenceHopping;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_SRSResource */
typedef struct NRPPA_SRSResource {
	NRPPA_SRSResourceID_t	 sRSResourceID;
	long	 nrofSRS_Ports;
	NRPPA_TransmissionComb_t	 transmissionComb;
	long	 startPosition;
	long	 nrofSymbols;
	long	 repetitionFactor;
	long	 freqDomainPosition;
	long	 freqDomainShift;
	long	 c_SRS;
	long	 b_SRS;
	long	 b_hop;
	long	 groupOrSequenceHopping;
	NRPPA_ResourceType_t	 resourceType;
	long	 slotOffset;
	long	 sequenceId;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SRSResource_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_nrofSRS_Ports_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_nrofSymbols_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_repetitionFactor_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_groupOrSequenceHopping_22;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SRSResource;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_SRSResource_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_SRSResource_1[16];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_SRSResource_H_ */
#include <asn_internal.h>
