/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-CommonDataTypes"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_PrivateIE_ID_H_
#define	_NRPPA_PrivateIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PrivateIE_ID_PR {
	NRPPA_PrivateIE_ID_PR_NOTHING,	/* No components present */
	NRPPA_PrivateIE_ID_PR_local,
	NRPPA_PrivateIE_ID_PR_global
} NRPPA_PrivateIE_ID_PR;

/* NRPPA_PrivateIE-ID */
typedef struct NRPPA_PrivateIE_ID {
	NRPPA_PrivateIE_ID_PR present;
	union NRPPA_PrivateIE_ID_u {
		long	 local;
		OBJECT_IDENTIFIER_t	 global;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PrivateIE_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PrivateIE_ID;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_PrivateIE_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PrivateIE_ID_1[2];
extern asn_per_constraints_t asn_PER_type_NRPPA_PrivateIE_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PrivateIE_ID_H_ */
#include <asn_internal.h>
