/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_MeasuredResultsValue_H_
#define	_NRPPA_MeasuredResultsValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_MeasuredResultsValue_PR {
	NRPPA_MeasuredResultsValue_PR_NOTHING,	/* No components present */
	NRPPA_MeasuredResultsValue_PR_valueAngleOfArrival_EUTRA,
	NRPPA_MeasuredResultsValue_PR_valueTimingAdvanceType1_EUTRA,
	NRPPA_MeasuredResultsValue_PR_valueTimingAdvanceType2_EUTRA,
	NRPPA_MeasuredResultsValue_PR_resultRSRP_EUTRA,
	NRPPA_MeasuredResultsValue_PR_resultRSRQ_EUTRA,
	NRPPA_MeasuredResultsValue_PR_measuredResultsValue_Extension
} NRPPA_MeasuredResultsValue_PR;

/* Forward declarations */
struct NRPPA_ResultRSRP_EUTRA;
struct NRPPA_ResultRSRQ_EUTRA;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_MeasuredResultsValue */
typedef struct NRPPA_MeasuredResultsValue {
	NRPPA_MeasuredResultsValue_PR present;
	union NRPPA_MeasuredResultsValue_u {
		long	 valueAngleOfArrival_EUTRA;
		long	 valueTimingAdvanceType1_EUTRA;
		long	 valueTimingAdvanceType2_EUTRA;
		struct NRPPA_ResultRSRP_EUTRA	*resultRSRP_EUTRA;
		struct NRPPA_ResultRSRQ_EUTRA	*resultRSRQ_EUTRA;
		struct NRPPA_ProtocolIE_Single_Container	*measuredResultsValue_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_MeasuredResultsValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasuredResultsValue;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_MeasuredResultsValue_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_MeasuredResultsValue_1[6];
extern asn_per_constraints_t asn_PER_type_NRPPA_MeasuredResultsValue_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_MeasuredResultsValue_H_ */
#include <asn_internal.h>
