/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Descriptions"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#include "NRPPA_SuccessfulOutcome.h"

static const long asn_VAL_1_NRPPA_id_e_CIDMeasurementInitiation = 2;
static const long asn_VAL_1_NRPPA_reject = 0;
static const long asn_VAL_2_NRPPA_id_oTDOAInformationExchange = 6;
static const long asn_VAL_2_NRPPA_reject = 0;
static const long asn_VAL_3_NRPPA_id_positioningInformationExchange = 9;
static const long asn_VAL_3_NRPPA_reject = 0;
static const long asn_VAL_4_NRPPA_id_Measurement = 11;
static const long asn_VAL_4_NRPPA_reject = 0;
static const long asn_VAL_5_NRPPA_id_tRPInformationExchange = 16;
static const long asn_VAL_5_NRPPA_reject = 0;
static const long asn_VAL_6_NRPPA_id_positioningActivation = 17;
static const long asn_VAL_6_NRPPA_reject = 0;
static const long asn_VAL_7_NRPPA_id_e_CIDMeasurementFailureIndication = 3;
static const long asn_VAL_7_NRPPA_ignore = 1;
static const long asn_VAL_8_NRPPA_id_e_CIDMeasurementReport = 4;
static const long asn_VAL_8_NRPPA_ignore = 1;
static const long asn_VAL_9_NRPPA_id_e_CIDMeasurementTermination = 5;
static const long asn_VAL_9_NRPPA_reject = 0;
static const long asn_VAL_10_NRPPA_id_errorIndication = 0;
static const long asn_VAL_10_NRPPA_ignore = 1;
static const long asn_VAL_11_NRPPA_id_privateMessage = 1;
static const long asn_VAL_11_NRPPA_ignore = 1;
static const long asn_VAL_12_NRPPA_id_assistanceInformationControl = 7;
static const long asn_VAL_12_NRPPA_reject = 0;
static const long asn_VAL_13_NRPPA_id_assistanceInformationFeedback = 8;
static const long asn_VAL_13_NRPPA_reject = 0;
static const long asn_VAL_14_NRPPA_id_positioningInformationUpdate = 10;
static const long asn_VAL_14_NRPPA_ignore = 1;
static const long asn_VAL_15_NRPPA_id_MeasurementReport = 12;
static const long asn_VAL_15_NRPPA_ignore = 1;
static const long asn_VAL_16_NRPPA_id_MeasurementUpdate = 13;
static const long asn_VAL_16_NRPPA_ignore = 1;
static const long asn_VAL_17_NRPPA_id_MeasurementAbort = 14;
static const long asn_VAL_17_NRPPA_ignore = 1;
static const long asn_VAL_18_NRPPA_id_MeasurementFailureIndication = 15;
static const long asn_VAL_18_NRPPA_ignore = 1;
static const long asn_VAL_19_NRPPA_id_positioningDeactivation = 18;
static const long asn_VAL_19_NRPPA_ignore = 1;
static const asn_ioc_cell_t asn_IOS_NRPPA_NRPPA_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_E_CIDMeasurementInitiationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_E_CIDMeasurementInitiationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_E_CIDMeasurementInitiationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_1_NRPPA_id_e_CIDMeasurementInitiation },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_1_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_OTDOAInformationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_OTDOAInformationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_OTDOAInformationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_2_NRPPA_id_oTDOAInformationExchange },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_2_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_PositioningInformationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_PositioningInformationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_PositioningInformationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_3_NRPPA_id_positioningInformationExchange },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_3_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_MeasurementRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_MeasurementResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_MeasurementFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_4_NRPPA_id_Measurement },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_4_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_TRPInformationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_TRPInformationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_TRPInformationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_5_NRPPA_id_tRPInformationExchange },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_5_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_PositioningActivationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_PositioningActivationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_NRPPA_PositioningActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_6_NRPPA_id_positioningActivation },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_6_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_E_CIDMeasurementFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_7_NRPPA_id_e_CIDMeasurementFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_7_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_E_CIDMeasurementReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_8_NRPPA_id_e_CIDMeasurementReport },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_8_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_E_CIDMeasurementTerminationCommand },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_9_NRPPA_id_e_CIDMeasurementTermination },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_9_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_ErrorIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_10_NRPPA_id_errorIndication },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_10_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_PrivateMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_11_NRPPA_id_privateMessage },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_11_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_AssistanceInformationControl },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_12_NRPPA_id_assistanceInformationControl },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_12_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_AssistanceInformationFeedback },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_13_NRPPA_id_assistanceInformationFeedback },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_13_NRPPA_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_PositioningInformationUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_14_NRPPA_id_positioningInformationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_14_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_MeasurementReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_15_NRPPA_id_MeasurementReport },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_15_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_MeasurementUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_16_NRPPA_id_MeasurementUpdate },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_16_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_MeasurementAbort },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_17_NRPPA_id_MeasurementAbort },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_17_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_MeasurementFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_18_NRPPA_id_MeasurementFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_18_NRPPA_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_NRPPA_PositioningDeactivation },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_NRPPA_ProcedureCode, &asn_VAL_19_NRPPA_id_positioningDeactivation },
	{ "&criticality", aioc__value, &asn_DEF_NRPPA_Criticality, &asn_VAL_19_NRPPA_ignore }
};
static const asn_ioc_set_t asn_IOS_NRPPA_NRPPA_ELEMENTARY_PROCEDURES_1[] = {
	{ 19, 5, asn_IOS_NRPPA_NRPPA_ELEMENTARY_PROCEDURES_1_rows }
};
static int
memb_NRPPA_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SuccessfulOutcome_NRPPA_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_NRPPA_NRPPA_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct NRPPA_SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_NRPPA_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_SuccessfulOutcome_NRPPA_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_NRPPA_NRPPA_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 1; /* &SuccessfulOutcome */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct NRPPA_SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_NRPPA_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPA_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPA_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_NRPPA_value_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_NRPPA_value_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome__value, choice.E_CIDMeasurementInitiationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPA_E_CIDMeasurementInitiationResponse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"E-CIDMeasurementInitiationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome__value, choice.OTDOAInformationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPA_OTDOAInformationResponse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"OTDOAInformationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome__value, choice.PositioningInformationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPA_PositioningInformationResponse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"PositioningInformationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome__value, choice.MeasurementResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPA_MeasurementResponse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"MeasurementResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome__value, choice.TRPInformationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPA_TRPInformationResponse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"TRPInformationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome__value, choice.PositioningActivationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRPPA_PositioningActivationResponse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"PositioningActivationResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPA_value_tag2el_5[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 5 }, /* E-CIDMeasurementInitiationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 4 }, /* OTDOAInformationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 3 }, /* PositioningInformationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 2 }, /* MeasurementResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 1 }, /* TRPInformationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 0 } /* PositioningActivationResponse */
};
static asn_CHOICE_specifics_t asn_SPC_NRPPA_value_specs_5 = {
	sizeof(struct NRPPA_SuccessfulOutcome__value),
	offsetof(struct NRPPA_SuccessfulOutcome__value, _asn_ctx),
	offsetof(struct NRPPA_SuccessfulOutcome__value, present),
	sizeof(((struct NRPPA_SuccessfulOutcome__value *)0)->present),
	asn_MAP_NRPPA_value_tag2el_5,
	6,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NRPPA_value_5 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_NRPPA_value_5,
	6,	/* Elements count */
	&asn_SPC_NRPPA_value_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NRPPA_SuccessfulOutcome_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPA_ProcedureCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPA_procedureCode_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPA_procedureCode_constraint_1
		},
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPA_Criticality,
		select_SuccessfulOutcome_NRPPA_criticality_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPA_criticality_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPA_criticality_constraint_1
		},
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome, nrppatransactionID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPA_NRPPATransactionID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nrppatransactionID"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct NRPPA_SuccessfulOutcome, value),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NRPPA_value_5,
		select_SuccessfulOutcome_NRPPA_value_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_NRPPA_value_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_NRPPA_value_constraint_1
		},
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_NRPPA_SuccessfulOutcome_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPA_SuccessfulOutcome_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nrppatransactionID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPA_SuccessfulOutcome_specs_1 = {
	sizeof(struct NRPPA_SuccessfulOutcome),
	offsetof(struct NRPPA_SuccessfulOutcome, _asn_ctx),
	asn_MAP_NRPPA_SuccessfulOutcome_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPA_SuccessfulOutcome = {
	"SuccessfulOutcome",
	"SuccessfulOutcome",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPA_SuccessfulOutcome_tags_1,
	sizeof(asn_DEF_NRPPA_SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_NRPPA_SuccessfulOutcome_tags_1[0]), /* 1 */
	asn_DEF_NRPPA_SuccessfulOutcome_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPA_SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_NRPPA_SuccessfulOutcome_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPA_SuccessfulOutcome_1,
	4,	/* Elements count */
	&asn_SPC_NRPPA_SuccessfulOutcome_specs_1	/* Additional specs */
};

