/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_ValueRSRQ_NR_H_
#define	_NRPPA_ValueRSRQ_NR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPA_ValueRSRQ-NR */
typedef long	 NRPPA_ValueRSRQ_NR_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_ValueRSRQ_NR_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ValueRSRQ_NR;
asn_struct_free_f NRPPA_ValueRSRQ_NR_free;
asn_struct_print_f NRPPA_ValueRSRQ_NR_print;
asn_constr_check_f NRPPA_ValueRSRQ_NR_constraint;
ber_type_decoder_f NRPPA_ValueRSRQ_NR_decode_ber;
der_type_encoder_f NRPPA_ValueRSRQ_NR_encode_der;
xer_type_decoder_f NRPPA_ValueRSRQ_NR_decode_xer;
xer_type_encoder_f NRPPA_ValueRSRQ_NR_encode_xer;
jer_type_encoder_f NRPPA_ValueRSRQ_NR_encode_jer;
per_type_decoder_f NRPPA_ValueRSRQ_NR_decode_uper;
per_type_encoder_f NRPPA_ValueRSRQ_NR_encode_uper;
per_type_decoder_f NRPPA_ValueRSRQ_NR_decode_aper;
per_type_encoder_f NRPPA_ValueRSRQ_NR_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ValueRSRQ_NR_H_ */
#include <asn_internal.h>
