/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_RequestedSRSTransmissionCharacteristics_H_
#define	_NRPPA_RequestedSRSTransmissionCharacteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "NRPPA_BandwidthSRS.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_RequestedSRSTransmissionCharacteristics__resourceType {
	NRPPA_RequestedSRSTransmissionCharacteristics__resourceType_periodic	= 0,
	NRPPA_RequestedSRSTransmissionCharacteristics__resourceType_semi_persistent	= 1,
	NRPPA_RequestedSRSTransmissionCharacteristics__resourceType_aperiodic	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_RequestedSRSTransmissionCharacteristics__resourceType;

/* Forward declarations */
struct NRPPA_SSBInfo;
struct NRPPA_ProtocolExtensionContainer;
struct NRPPA_SRSResourceSet_Item;

/* NRPPA_RequestedSRSTransmissionCharacteristics */
typedef struct NRPPA_RequestedSRSTransmissionCharacteristics {
	long	*numberOfTransmissions;	/* OPTIONAL */
	long	 resourceType;
	NRPPA_BandwidthSRS_t	 bandwidth;
	struct NRPPA_RequestedSRSTransmissionCharacteristics__listOfSRSResourceSet {
		A_SEQUENCE_OF(struct NRPPA_SRSResourceSet_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfSRSResourceSet;
	struct NRPPA_SSBInfo	*sSBInformation;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_RequestedSRSTransmissionCharacteristics_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_resourceType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_RequestedSRSTransmissionCharacteristics;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_RequestedSRSTransmissionCharacteristics_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_RequestedSRSTransmissionCharacteristics_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_RequestedSRSTransmissionCharacteristics_H_ */
#include <asn_internal.h>
