/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_ResultEUTRA_Item_H_
#define	_NRPPA_ResultEUTRA_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_PCI-EUTRA.h"
#include "NRPPA_EARFCN.h"
#include "NRPPA_ValueRSRP-EUTRA.h"
#include "NRPPA_ValueRSRQ-EUTRA.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_CGI_EUTRA;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_ResultEUTRA-Item */
typedef struct NRPPA_ResultEUTRA_Item {
	NRPPA_PCI_EUTRA_t	 pCI_EUTRA;
	NRPPA_EARFCN_t	 eARFCN;
	NRPPA_ValueRSRP_EUTRA_t	*valueRSRP_EUTRA;	/* OPTIONAL */
	NRPPA_ValueRSRQ_EUTRA_t	*valueRSRQ_EUTRA;	/* OPTIONAL */
	struct NRPPA_CGI_EUTRA	*cGI_EUTRA;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResultEUTRA_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResultEUTRA_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResultEUTRA_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResultEUTRA_Item_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResultEUTRA_Item_H_ */
#include <asn_internal.h>
