/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_PosResourceSetType_H_
#define	_NRPPA_PosResourceSetType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PosResourceSetType_PR {
	NRPPA_PosResourceSetType_PR_NOTHING,	/* No components present */
	NRPPA_PosResourceSetType_PR_periodic,
	NRPPA_PosResourceSetType_PR_semi_persistent,
	NRPPA_PosResourceSetType_PR_aperiodic,
	NRPPA_PosResourceSetType_PR_choice_extension
} NRPPA_PosResourceSetType_PR;

/* Forward declarations */
struct NRPPA_PosResourceSetTypePeriodic;
struct NRPPA_PosResourceSetTypeSemi_persistent;
struct NRPPA_PosResourceSetTypeAperiodic;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_PosResourceSetType */
typedef struct NRPPA_PosResourceSetType {
	NRPPA_PosResourceSetType_PR present;
	union NRPPA_PosResourceSetType_u {
		struct NRPPA_PosResourceSetTypePeriodic	*periodic;
		struct NRPPA_PosResourceSetTypeSemi_persistent	*semi_persistent;
		struct NRPPA_PosResourceSetTypeAperiodic	*aperiodic;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PosResourceSetType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PosResourceSetType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_PosResourceSetType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PosResourceSetType_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPA_PosResourceSetType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PosResourceSetType_H_ */
#include <asn_internal.h>
