/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_ReferenceSignal_H_
#define	_NRPPA_ReferenceSignal_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_NZP-CSI-RS-ResourceID.h"
#include "NRPPA_SRSResourceID.h"
#include "NRPPA_SRSPosResourceID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ReferenceSignal_PR {
	NRPPA_ReferenceSignal_PR_NOTHING,	/* No components present */
	NRPPA_ReferenceSignal_PR_nZP_CSI_RS,
	NRPPA_ReferenceSignal_PR_sSB,
	NRPPA_ReferenceSignal_PR_sRS,
	NRPPA_ReferenceSignal_PR_positioningSRS,
	NRPPA_ReferenceSignal_PR_dL_PRS,
	NRPPA_ReferenceSignal_PR_choice_Extension
} NRPPA_ReferenceSignal_PR;

/* Forward declarations */
struct NRPPA_SSB;
struct NRPPA_DL_PRS;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_ReferenceSignal */
typedef struct NRPPA_ReferenceSignal {
	NRPPA_ReferenceSignal_PR present;
	union NRPPA_ReferenceSignal_u {
		NRPPA_NZP_CSI_RS_ResourceID_t	 nZP_CSI_RS;
		struct NRPPA_SSB	*sSB;
		NRPPA_SRSResourceID_t	 sRS;
		NRPPA_SRSPosResourceID_t	 positioningSRS;
		struct NRPPA_DL_PRS	*dL_PRS;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ReferenceSignal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ReferenceSignal;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_ReferenceSignal_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ReferenceSignal_1[6];
extern asn_per_constraints_t asn_PER_type_NRPPA_ReferenceSignal_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ReferenceSignal_H_ */
#include <asn_internal.h>
