/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-CommonDataTypes"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_ProcedureCode_H_
#define	_NRPPA_ProcedureCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPA_ProcedureCode */
typedef long	 NRPPA_ProcedureCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_ProcedureCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ProcedureCode;
asn_struct_free_f NRPPA_ProcedureCode_free;
asn_struct_print_f NRPPA_ProcedureCode_print;
asn_constr_check_f NRPPA_ProcedureCode_constraint;
ber_type_decoder_f NRPPA_ProcedureCode_decode_ber;
der_type_encoder_f NRPPA_ProcedureCode_encode_der;
xer_type_decoder_f NRPPA_ProcedureCode_decode_xer;
xer_type_encoder_f NRPPA_ProcedureCode_encode_xer;
jer_type_encoder_f NRPPA_ProcedureCode_encode_jer;
per_type_decoder_f NRPPA_ProcedureCode_decode_uper;
per_type_encoder_f NRPPA_ProcedureCode_encode_uper;
per_type_decoder_f NRPPA_ProcedureCode_decode_aper;
per_type_encoder_f NRPPA_ProcedureCode_encode_aper;
#define NRPPA_ProcedureCode_id_errorIndication	((NRPPA_ProcedureCode_t)0)
#define NRPPA_ProcedureCode_id_privateMessage	((NRPPA_ProcedureCode_t)1)
#define NRPPA_ProcedureCode_id_e_CIDMeasurementInitiation	((NRPPA_ProcedureCode_t)2)
#define NRPPA_ProcedureCode_id_e_CIDMeasurementFailureIndication	((NRPPA_ProcedureCode_t)3)
#define NRPPA_ProcedureCode_id_e_CIDMeasurementReport	((NRPPA_ProcedureCode_t)4)
#define NRPPA_ProcedureCode_id_e_CIDMeasurementTermination	((NRPPA_ProcedureCode_t)5)
#define NRPPA_ProcedureCode_id_oTDOAInformationExchange	((NRPPA_ProcedureCode_t)6)
#define NRPPA_ProcedureCode_id_assistanceInformationControl	((NRPPA_ProcedureCode_t)7)
#define NRPPA_ProcedureCode_id_assistanceInformationFeedback	((NRPPA_ProcedureCode_t)8)
#define NRPPA_ProcedureCode_id_positioningInformationExchange	((NRPPA_ProcedureCode_t)9)
#define NRPPA_ProcedureCode_id_positioningInformationUpdate	((NRPPA_ProcedureCode_t)10)
#define NRPPA_ProcedureCode_id_Measurement	((NRPPA_ProcedureCode_t)11)
#define NRPPA_ProcedureCode_id_MeasurementReport	((NRPPA_ProcedureCode_t)12)
#define NRPPA_ProcedureCode_id_MeasurementUpdate	((NRPPA_ProcedureCode_t)13)
#define NRPPA_ProcedureCode_id_MeasurementAbort	((NRPPA_ProcedureCode_t)14)
#define NRPPA_ProcedureCode_id_MeasurementFailureIndication	((NRPPA_ProcedureCode_t)15)
#define NRPPA_ProcedureCode_id_tRPInformationExchange	((NRPPA_ProcedureCode_t)16)
#define NRPPA_ProcedureCode_id_positioningActivation	((NRPPA_ProcedureCode_t)17)
#define NRPPA_ProcedureCode_id_positioningDeactivation	((NRPPA_ProcedureCode_t)18)

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ProcedureCode_H_ */
#include <asn_internal.h>
