/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Descriptions"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_InitiatingMessage_H_
#define	_NRPPA_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_ProcedureCode.h"
#include "NRPPA_Criticality.h"
#include "NRPPA_NRPPATransactionID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "NRPPA_E-CIDMeasurementInitiationRequest.h"
#include "NRPPA_E-CIDMeasurementInitiationResponse.h"
#include "NRPPA_E-CIDMeasurementInitiationFailure.h"
#include "NRPPA_OTDOAInformationRequest.h"
#include "NRPPA_OTDOAInformationResponse.h"
#include "NRPPA_OTDOAInformationFailure.h"
#include "NRPPA_PositioningInformationRequest.h"
#include "NRPPA_PositioningInformationResponse.h"
#include "NRPPA_PositioningInformationFailure.h"
#include "NRPPA_MeasurementRequest.h"
#include "NRPPA_MeasurementResponse.h"
#include "NRPPA_MeasurementFailure.h"
#include "NRPPA_TRPInformationRequest.h"
#include "NRPPA_TRPInformationResponse.h"
#include "NRPPA_TRPInformationFailure.h"
#include "NRPPA_PositioningActivationRequest.h"
#include "NRPPA_PositioningActivationResponse.h"
#include "NRPPA_PositioningActivationFailure.h"
#include "NRPPA_E-CIDMeasurementFailureIndication.h"
#include "NRPPA_E-CIDMeasurementReport.h"
#include "NRPPA_E-CIDMeasurementTerminationCommand.h"
#include "NRPPA_ErrorIndication.h"
#include "NRPPA_PrivateMessage.h"
#include "NRPPA_AssistanceInformationControl.h"
#include "NRPPA_AssistanceInformationFeedback.h"
#include "NRPPA_PositioningInformationUpdate.h"
#include "NRPPA_MeasurementReport.h"
#include "NRPPA_MeasurementUpdate.h"
#include "NRPPA_MeasurementAbort.h"
#include "NRPPA_MeasurementFailureIndication.h"
#include "NRPPA_PositioningDeactivation.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_InitiatingMessage__value_PR {
	NRPPA_InitiatingMessage__value_PR_NOTHING,	/* No components present */
	NRPPA_InitiatingMessage__value_PR_E_CIDMeasurementInitiationRequest,
	NRPPA_InitiatingMessage__value_PR_OTDOAInformationRequest,
	NRPPA_InitiatingMessage__value_PR_PositioningInformationRequest,
	NRPPA_InitiatingMessage__value_PR_MeasurementRequest,
	NRPPA_InitiatingMessage__value_PR_TRPInformationRequest,
	NRPPA_InitiatingMessage__value_PR_PositioningActivationRequest,
	NRPPA_InitiatingMessage__value_PR_E_CIDMeasurementFailureIndication,
	NRPPA_InitiatingMessage__value_PR_E_CIDMeasurementReport,
	NRPPA_InitiatingMessage__value_PR_E_CIDMeasurementTerminationCommand,
	NRPPA_InitiatingMessage__value_PR_ErrorIndication,
	NRPPA_InitiatingMessage__value_PR_PrivateMessage,
	NRPPA_InitiatingMessage__value_PR_AssistanceInformationControl,
	NRPPA_InitiatingMessage__value_PR_AssistanceInformationFeedback,
	NRPPA_InitiatingMessage__value_PR_PositioningInformationUpdate,
	NRPPA_InitiatingMessage__value_PR_MeasurementReport,
	NRPPA_InitiatingMessage__value_PR_MeasurementUpdate,
	NRPPA_InitiatingMessage__value_PR_MeasurementAbort,
	NRPPA_InitiatingMessage__value_PR_MeasurementFailureIndication,
	NRPPA_InitiatingMessage__value_PR_PositioningDeactivation
} NRPPA_InitiatingMessage__value_PR;

/* NRPPA_InitiatingMessage */
typedef struct NRPPA_InitiatingMessage {
	NRPPA_ProcedureCode_t	 procedureCode;
	NRPPA_Criticality_t	 criticality;
	NRPPA_NRPPATransactionID_t	 nrppatransactionID;
	struct NRPPA_InitiatingMessage__value {
		NRPPA_InitiatingMessage__value_PR present;
		union NRPPA_InitiatingMessage__NRPPA_value_u {
			NRPPA_E_CIDMeasurementInitiationRequest_t	 E_CIDMeasurementInitiationRequest;
			NRPPA_OTDOAInformationRequest_t	 OTDOAInformationRequest;
			NRPPA_PositioningInformationRequest_t	 PositioningInformationRequest;
			NRPPA_MeasurementRequest_t	 MeasurementRequest;
			NRPPA_TRPInformationRequest_t	 TRPInformationRequest;
			NRPPA_PositioningActivationRequest_t	 PositioningActivationRequest;
			NRPPA_E_CIDMeasurementFailureIndication_t	 E_CIDMeasurementFailureIndication;
			NRPPA_E_CIDMeasurementReport_t	 E_CIDMeasurementReport;
			NRPPA_E_CIDMeasurementTerminationCommand_t	 E_CIDMeasurementTerminationCommand;
			NRPPA_ErrorIndication_t	 ErrorIndication;
			NRPPA_PrivateMessage_t	 PrivateMessage;
			NRPPA_AssistanceInformationControl_t	 AssistanceInformationControl;
			NRPPA_AssistanceInformationFeedback_t	 AssistanceInformationFeedback;
			NRPPA_PositioningInformationUpdate_t	 PositioningInformationUpdate;
			NRPPA_MeasurementReport_t	 MeasurementReport;
			NRPPA_MeasurementUpdate_t	 MeasurementUpdate;
			NRPPA_MeasurementAbort_t	 MeasurementAbort;
			NRPPA_MeasurementFailureIndication_t	 MeasurementFailureIndication;
			NRPPA_PositioningDeactivation_t	 PositioningDeactivation;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_InitiatingMessage_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_InitiatingMessage_H_ */
#include <asn_internal.h>
