/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Descriptions"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_NRPPA_PDU_H_
#define	_NRPPA_NRPPA_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_NRPPA_PDU_PR {
	NRPPA_NRPPA_PDU_PR_NOTHING,	/* No components present */
	NRPPA_NRPPA_PDU_PR_initiatingMessage,
	NRPPA_NRPPA_PDU_PR_successfulOutcome,
	NRPPA_NRPPA_PDU_PR_unsuccessfulOutcome
	/* Extensions may appear below */
	
} NRPPA_NRPPA_PDU_PR;

/* Forward declarations */
struct NRPPA_InitiatingMessage;
struct NRPPA_SuccessfulOutcome;
struct NRPPA_UnsuccessfulOutcome;

/* NRPPA_NRPPA-PDU */
typedef struct NRPPA_NRPPA_PDU {
	NRPPA_NRPPA_PDU_PR present;
	union NRPPA_NRPPA_PDU_u {
		struct NRPPA_InitiatingMessage	*initiatingMessage;
		struct NRPPA_SuccessfulOutcome	*successfulOutcome;
		struct NRPPA_UnsuccessfulOutcome	*unsuccessfulOutcome;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_NRPPA_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_NRPPA_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_NRPPA_PDU_H_ */
#include <asn_internal.h>
