/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_WLANMeasurementResult_Item_H_
#define	_NRPPA_WLANMeasurementResult_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_WLAN-RSSI.h"
#include "NRPPA_SSID.h"
#include "NRPPA_BSSID.h"
#include "NRPPA_HESSID.h"
#include "NRPPA_WLANOperatingClass.h"
#include "NRPPA_WLANCountryCode.h"
#include "NRPPA_WLANBand.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_WLANChannelList;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_WLANMeasurementResult-Item */
typedef struct NRPPA_WLANMeasurementResult_Item {
	NRPPA_WLAN_RSSI_t	 wLAN_RSSI;
	NRPPA_SSID_t	*sSID;	/* OPTIONAL */
	NRPPA_BSSID_t	*bSSID;	/* OPTIONAL */
	NRPPA_HESSID_t	*hESSID;	/* OPTIONAL */
	NRPPA_WLANOperatingClass_t	*operatingClass;	/* OPTIONAL */
	NRPPA_WLANCountryCode_t	*countryCode;	/* OPTIONAL */
	struct NRPPA_WLANChannelList	*wLANChannelList;	/* OPTIONAL */
	NRPPA_WLANBand_t	*wLANBand;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_WLANMeasurementResult_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_WLANMeasurementResult_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_WLANMeasurementResult_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_WLANMeasurementResult_Item_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_WLANMeasurementResult_Item_H_ */
#include <asn_internal.h>
