/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_PosSRSResource_Item_H_
#define	_NRPPA_PosSRSResource_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_SRSPosResourceID.h"
#include "NRPPA_TransmissionCombPos.h"
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "NRPPA_ResourceTypePos.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PosSRSResource_Item__nrofSymbols {
	NRPPA_PosSRSResource_Item__nrofSymbols_n1	= 0,
	NRPPA_PosSRSResource_Item__nrofSymbols_n2	= 1,
	NRPPA_PosSRSResource_Item__nrofSymbols_n4	= 2,
	NRPPA_PosSRSResource_Item__nrofSymbols_n8	= 3,
	NRPPA_PosSRSResource_Item__nrofSymbols_n12	= 4
} e_NRPPA_PosSRSResource_Item__nrofSymbols;
typedef enum NRPPA_PosSRSResource_Item__groupOrSequenceHopping {
	NRPPA_PosSRSResource_Item__groupOrSequenceHopping_neither	= 0,
	NRPPA_PosSRSResource_Item__groupOrSequenceHopping_groupHopping	= 1,
	NRPPA_PosSRSResource_Item__groupOrSequenceHopping_sequenceHopping	= 2
} e_NRPPA_PosSRSResource_Item__groupOrSequenceHopping;

/* Forward declarations */
struct NRPPA_SpatialRelationPos;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_PosSRSResource-Item */
typedef struct NRPPA_PosSRSResource_Item {
	NRPPA_SRSPosResourceID_t	 srs_PosResourceId;
	NRPPA_TransmissionCombPos_t	 transmissionCombPos;
	long	 startPosition;
	long	 nrofSymbols;
	long	 freqDomainShift;
	long	 c_SRS;
	long	 groupOrSequenceHopping;
	NRPPA_ResourceTypePos_t	 resourceTypePos;
	long	 sequenceId;
	struct NRPPA_SpatialRelationPos	*spatialRelationPos;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PosSRSResource_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_nrofSymbols_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_groupOrSequenceHopping_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PosSRSResource_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PosSRSResource_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PosSRSResource_Item_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PosSRSResource_Item_H_ */
#include <asn_internal.h>
