/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_UL_AoA_H_
#define	_NRPPA_UL_AoA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_UL_AoA__angleCoordinateSystem {
	NRPPA_UL_AoA__angleCoordinateSystem_lCS	= 0,
	NRPPA_UL_AoA__angleCoordinateSystem_gCS	= 1
} e_NRPPA_UL_AoA__angleCoordinateSystem;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_UL-AoA */
typedef struct NRPPA_UL_AoA {
	long	 azimuthAoA;
	long	*zenithAoA;	/* OPTIONAL */
	long	*angleCoordinateSystem;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_UL_AoA_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_angleCoordinateSystem_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_UL_AoA;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_UL_AoA_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_UL_AoA_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_UL_AoA_H_ */
#include <asn_internal.h>
