/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_OTDOACell_Information_Item_H_
#define	_NRPPA_OTDOACell_Information_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_PCI-EUTRA.h"
#include "NRPPA_TAC.h"
#include "NRPPA_EARFCN.h"
#include "NRPPA_PRS-Bandwidth-EUTRA.h"
#include "NRPPA_PRS-ConfigurationIndex-EUTRA.h"
#include "NRPPA_CPLength-EUTRA.h"
#include "NRPPA_NumberOfDlFrames-EUTRA.h"
#include "NRPPA_NumberOfAntennaPorts-EUTRA.h"
#include "NRPPA_SFNInitialisationTime-EUTRA.h"
#include "NRPPA_PRS-ID-EUTRA.h"
#include "NRPPA_TP-ID-EUTRA.h"
#include "NRPPA_TP-Type-EUTRA.h"
#include "NRPPA_NumberOfDlFrames-Extended-EUTRA.h"
#include "NRPPA_DL-Bandwidth-EUTRA.h"
#include "NRPPA_PRSOccasionGroup-EUTRA.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_OTDOACell_Information_Item_PR {
	NRPPA_OTDOACell_Information_Item_PR_NOTHING,	/* No components present */
	NRPPA_OTDOACell_Information_Item_PR_pCI_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_cGI_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_tAC,
	NRPPA_OTDOACell_Information_Item_PR_eARFCN,
	NRPPA_OTDOACell_Information_Item_PR_pRS_Bandwidth_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_pRS_ConfigurationIndex_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_cPLength_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_numberOfDlFrames_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_numberOfAntennaPorts_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_sFNInitialisationTime_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_nG_RANAccessPointPosition,
	NRPPA_OTDOACell_Information_Item_PR_pRSMutingConfiguration_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_prsid_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_tpid_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_tpType_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_numberOfDlFrames_Extended_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_crsCPlength_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_dL_Bandwidth_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_pRSOccasionGroup_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_pRSFrequencyHoppingConfiguration_EUTRA,
	NRPPA_OTDOACell_Information_Item_PR_oTDOACell_Information_Item_Extension
} NRPPA_OTDOACell_Information_Item_PR;

/* Forward declarations */
struct NRPPA_CGI_EUTRA;
struct NRPPA_NG_RANAccessPointPosition;
struct NRPPA_PRSMutingConfiguration_EUTRA;
struct NRPPA_PRSFrequencyHoppingConfiguration_EUTRA;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_OTDOACell-Information-Item */
typedef struct NRPPA_OTDOACell_Information_Item {
	NRPPA_OTDOACell_Information_Item_PR present;
	union NRPPA_OTDOACell_Information_Item_u {
		NRPPA_PCI_EUTRA_t	 pCI_EUTRA;
		struct NRPPA_CGI_EUTRA	*cGI_EUTRA;
		NRPPA_TAC_t	 tAC;
		NRPPA_EARFCN_t	 eARFCN;
		NRPPA_PRS_Bandwidth_EUTRA_t	 pRS_Bandwidth_EUTRA;
		NRPPA_PRS_ConfigurationIndex_EUTRA_t	 pRS_ConfigurationIndex_EUTRA;
		NRPPA_CPLength_EUTRA_t	 cPLength_EUTRA;
		NRPPA_NumberOfDlFrames_EUTRA_t	 numberOfDlFrames_EUTRA;
		NRPPA_NumberOfAntennaPorts_EUTRA_t	 numberOfAntennaPorts_EUTRA;
		NRPPA_SFNInitialisationTime_EUTRA_t	 sFNInitialisationTime_EUTRA;
		struct NRPPA_NG_RANAccessPointPosition	*nG_RANAccessPointPosition;
		struct NRPPA_PRSMutingConfiguration_EUTRA	*pRSMutingConfiguration_EUTRA;
		NRPPA_PRS_ID_EUTRA_t	 prsid_EUTRA;
		NRPPA_TP_ID_EUTRA_t	 tpid_EUTRA;
		NRPPA_TP_Type_EUTRA_t	 tpType_EUTRA;
		NRPPA_NumberOfDlFrames_Extended_EUTRA_t	 numberOfDlFrames_Extended_EUTRA;
		NRPPA_CPLength_EUTRA_t	 crsCPlength_EUTRA;
		NRPPA_DL_Bandwidth_EUTRA_t	 dL_Bandwidth_EUTRA;
		NRPPA_PRSOccasionGroup_EUTRA_t	 pRSOccasionGroup_EUTRA;
		struct NRPPA_PRSFrequencyHoppingConfiguration_EUTRA	*pRSFrequencyHoppingConfiguration_EUTRA;
		struct NRPPA_ProtocolIE_Single_Container	*oTDOACell_Information_Item_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_OTDOACell_Information_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OTDOACell_Information_Item;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_OTDOACell_Information_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_OTDOACell_Information_Item_1[21];
extern asn_per_constraints_t asn_PER_type_NRPPA_OTDOACell_Information_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_OTDOACell_Information_Item_H_ */
#include <asn_internal.h>
