/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_SSBBurstPosition_H_
#define	_NRPPA_SSBBurstPosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_SSBBurstPosition_PR {
	NRPPA_SSBBurstPosition_PR_NOTHING,	/* No components present */
	NRPPA_SSBBurstPosition_PR_shortBitmap,
	NRPPA_SSBBurstPosition_PR_mediumBitmap,
	NRPPA_SSBBurstPosition_PR_longBitmap
	/* Extensions may appear below */
	
} NRPPA_SSBBurstPosition_PR;

/* NRPPA_SSBBurstPosition */
typedef struct NRPPA_SSBBurstPosition {
	NRPPA_SSBBurstPosition_PR present;
	union NRPPA_SSBBurstPosition_u {
		BIT_STRING_t	 shortBitmap;
		BIT_STRING_t	 mediumBitmap;
		BIT_STRING_t	 longBitmap;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SSBBurstPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SSBBurstPosition;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_SSBBurstPosition_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_SSBBurstPosition_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_SSBBurstPosition_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_SSBBurstPosition_H_ */
#include <asn_internal.h>
