/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/home/kade-ddnkv/openairinterface5g/openair3/NRPPA/MESSAGES/ASN1/38455.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/kade-ddnkv/openairinterface5g/openair3/NRPPA/build/MESSAGES`
 */

#ifndef	_NRPPA_PosResourceSetTypeSemi_persistent_H_
#define	_NRPPA_PosResourceSetTypeSemi_persistent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PosResourceSetTypeSemi_persistent__possemi_persistentSet {
	NRPPA_PosResourceSetTypeSemi_persistent__possemi_persistentSet_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_PosResourceSetTypeSemi_persistent__possemi_persistentSet;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_PosResourceSetTypeSemi-persistent */
typedef struct NRPPA_PosResourceSetTypeSemi_persistent {
	long	 possemi_persistentSet;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PosResourceSetTypeSemi_persistent_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_possemi_persistentSet_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PosResourceSetTypeSemi_persistent;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PosResourceSetTypeSemi_persistent_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PosResourceSetTypeSemi_persistent_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PosResourceSetTypeSemi_persistent_H_ */
#include <asn_internal.h>
